// ============================================================
//  自私的基因（The Selfish Gene）· 沉浸式閱讀資料（中英雙語）
//  作者 Richard Dawkins 在世，本書仍在著作權保護期內：
//  各章正文為原創之論點重述（非原著文字）；金句為極短引用附出處與評析。
//  文字欄位多為 { zh, en }，由 engine 依語言切換鈕選取。
// ============================================================

const BOOK = {
  slug: 'selfishgene',
  langs: ['zh', 'en'],
  title: { zh: '自私的基因', en: 'The Selfish Gene' },
  author: 'Richard Dawkins',
  theme: {
    'bg-primary': '#0f1518', 'bg-secondary': '#151d20', 'bg-card': '#1b2429', 'bg-elevated': '#243036',
    'text-primary': '#e2e8e4', 'text-secondary': '#a4b0ab', 'text-muted': '#74807b',
    'accent': '#4fb89a', 'accent-light': '#7fd6bc', 'accent-glow': 'rgba(79,184,154,0.26)',
    'rose': '#c77b6b', 'jade': '#6fae8a', 'blue': '#5f9bc0', 'gold': '#c2a86a',
    'border': 'rgba(79,184,154,0.16)',
    atmosphere: { fall: 18, streak: 0, fallRadius: '50%' },
    dayMode: { 'bg-primary': '#eaf0ec', 'bg-secondary': '#e0e8e3', 'bg-card': '#f7fbf8', 'bg-elevated': '#eef4f0', 'text-primary': '#1f2b26', 'text-secondary': '#45524c', 'text-muted': '#71807a', 'border': 'rgba(50,120,95,0.22)' }
  },
  cover: {
    seal: '基',
    subtitle: { zh: 'The Selfish Gene', en: '自 私 的 基 因' },
    desc: {
      zh: '生命的主角，不是物種，不是群體，甚至不是你我，<br>而是那個看不見、卻近乎不朽的複製者——基因。<br>我們不過是它為了讓自己延續，而打造出來的「生存機器」。<br>這是一場把演化整個翻轉過來看的思想革命。',
      en: 'The true protagonist of life is not the species, nor the group, nor even you and me — but the invisible, near-immortal replicator: the gene.<br>We are merely the survival machines it builds to perpetuate itself.<br>This is a revolution that turns our whole view of evolution around.'
    }
  },
  musicPrompt: { zh: '準備好從「基因的視角」重看生命了嗎？<br>是否播放一段背景音樂？', en: 'Ready to see life from the gene’s-eye view?<br>Play some background music?' },
  intro: {
    subtitle: { zh: '在閱讀之前，先掌握這本書的骨架與核心主張', en: 'Grasp the book’s structure and core claim before you read' },
    author: { name: { zh: '理查·道金斯　Richard Dawkins', en: 'Richard Dawkins' }, portrait: 'D',
      years: { zh: '1941 — · 英國演化生物學家 · 牛津大學', en: '1941 — · British evolutionary biologist · Oxford' },
      bio: { zh: '英國演化生物學家、科普作家，牛津大學教授。1976 年出版的《自私的基因》讓「基因視角」的演化觀廣為人知，也首創了「迷因（meme）」一詞。他文筆犀利清晰，擅長把艱深的演化理論寫成人人能讀的思想探險，是二十世紀最具影響力的科普作家之一。',
        en: 'A British evolutionary biologist and science writer, professor at Oxford. His 1976 book "The Selfish Gene" popularized the gene’s-eye view of evolution and coined the word "meme." Sharp and lucid, he turns difficult evolutionary theory into an adventure any reader can follow — one of the most influential science writers of the twentieth century.' } },
    cards: [
      { icon: '🧬', title: { zh: '一句話核心', en: 'The core, in one line' }, text: { zh: '天擇的真正單位不是物種、群體或個體，而是「基因」。我們的身體只是基因為了複製自己而打造、駕駛的「生存機器」。', en: 'The true unit of natural selection is not the species, group, or individual, but the gene. Our bodies are merely the survival machines it builds and drives to copy itself.' } },
      { icon: '🧭', title: { zh: '為何顛覆', en: 'Why it upends things' }, text: { zh: '它把「為了物種好」的舊思路整個翻掉——看似利他的行為，底層往往是基因在為「自己的拷貝」精打細算。連無私都能從自私中演化出來。', en: 'It overturns the old "for the good of the species" thinking: behaviour that looks altruistic is often genes calculating for their own copies. Even selflessness can evolve out of selfishness.' } },
      { icon: '🔬', title: { zh: '一路推進', en: 'The through-line' }, text: { zh: '從生命起源的「複製者」，到親屬選擇、互惠、演化穩定策略；再到文化的複製者「迷因」，與基因伸出體外的「延伸表現型」。', en: 'From the first "replicator" at life’s origin, through kin selection, reciprocity, and the ESS; on to culture’s replicator, the "meme," and the gene’s reach beyond the body — the "extended phenotype."' } },
      { icon: '🎯', title: { zh: '閱讀建議', en: 'How to read it' }, text: { zh: '先在「概念譜」認識自私的基因、生存機器、利他與 ESS，再對照「思想軸」看它的學術脈絡。逐章抓：論點、論證、關鍵實例。', en: 'Start with the Concept map (selfish gene, survival machine, altruism, ESS), then use the Timeline for context. In each chapter grab: the claim, the argument, the key example.' } }
    ],
    guide: [
      { h: { zh: '先換上「基因的眼睛」', en: 'Put on the gene’s eyes' }, p: { zh: '到「概念譜」理解全書最關鍵的一招：把演化的主角從「個體」換成「基因」，很多謎題就迎刃而解。', en: 'In the Concept map, get the book’s key move: swap the protagonist of evolution from the individual to the gene, and many puzzles dissolve.' } },
      { h: { zh: '對照思想軸', en: 'Follow the timeline' }, p: { zh: '打開「思想軸」，看漢彌爾頓、特里弗斯、梅納德·史密斯的理論如何被道金斯綜合成一本書。', en: 'Open the Timeline to see how Hamilton, Trivers, and Maynard Smith’s ideas were synthesized by Dawkins into one book.' } },
      { h: { zh: '逐章抓三件事', en: 'Grab three things per chapter' }, p: { zh: '每章問：①核心論點？②怎麼論證？③舉了哪個關鍵實例？「閱讀」模組已替你拆成這三塊。', en: 'For each chapter ask: (1) the core claim, (2) the argument, (3) the key example. The Reader already splits every chapter into these three blocks.' } },
      { h: { zh: '從主題回看全局', en: 'Zoom out with the themes' }, p: { zh: '讀完到「主題」模組，把散落各章的洞見收攏成六條主線。', en: 'Afterwards, use the Themes to gather scattered insights into six threads.' } },
      { h: { zh: '別誤讀「自私」', en: 'Don’t misread “selfish”' }, p: { zh: '記住：「自私」是描述基因被複製的傾向，不是叫人自私；道金斯結尾反而呼籲我們反抗複製者、學習利他。', en: 'Remember: "selfish" describes the gene’s tendency to get copied, not a prescription for people. Dawkins ends by urging us to rebel against the replicators and learn altruism.' } }
    ]
  },
  labels: {
    nav: { characters: { zh: '概念譜', en: 'Concepts' }, timeline: { zh: '思想軸', en: 'Timeline' } },
    headers: { characters: { zh: '核心概念', en: 'Core Concepts' }, timeline: { zh: '演化思想軸', en: 'A Timeline of the Idea' } },
    subheads: { characters: { zh: '點擊概念卡或關係圖，看每個機制如何運作', en: 'Click a concept card or a node to see how each mechanism works' }, timeline: { zh: '從達爾文到延伸的表現型：基因視角的思想脈絡', en: 'From Darwin to the extended phenotype: the arc of the gene’s-eye view' } },
    timelineTypes: { history: { zh: '科學里程碑', en: 'Milestone' }, novel: { zh: '書中對應', en: 'In the book' }, character: { zh: '關鍵理論', en: 'Key theory' } },
    charDetail: { intro: { zh: '概念說明', en: 'What it is' }, analysis: { zh: '深入解讀', en: 'Deeper reading' }, related: { zh: '相關概念', en: 'Related concepts' }, tags: { zh: '關鍵標籤', en: 'Tags' }, empty: '—' },
    legend: { lead: { zh: '核心概念', en: 'Core concept' }, major: { zh: '重要概念', en: 'Key concept' }, minor: { zh: '次要概念', en: 'Secondary' }, edge: { zh: '概念關聯', en: 'Concept link' } }
  },
  families: [ { id: 'gene', label: { zh: '基因視角', en: 'Gene’s-Eye View' } }, { id: 'behavior', label: { zh: '行為與策略', en: 'Behaviour & Strategy' } }, { id: 'beyond', label: { zh: '超越基因', en: 'Beyond the Gene' } } ],
  graph: {
    title: { zh: '— 自 私 的 基 因 與 它 的 策 略 —', en: '— The Selfish Gene and Its Strategies —' },
    nodes: [
      { id: 'selfishgene', label: { zh: '自私的基因', en: 'Selfish Gene' }, x: 400, y: 110, tier: 'lead', color: '#4fb89a' },
      { id: 'replicator', label: { zh: '複製者', en: 'Replicator' }, x: 190, y: 130, tier: 'major', color: '#4fb89a' },
      { id: 'survivalmachine', label: { zh: '生存機器', en: 'Survival Machine' }, x: 235, y: 245, tier: 'major', color: '#4fb89a' },
      { id: 'altruism', label: { zh: '利他行為', en: 'Altruism' }, x: 400, y: 250, tier: 'major', color: '#6fae8a' },
      { id: 'kinselection', label: { zh: '親屬選擇', en: 'Kin Selection' }, x: 500, y: 350, tier: 'major', color: '#6fae8a' },
      { id: 'reciprocal', label: { zh: '互惠利他', en: 'Reciprocity' }, x: 380, y: 400, tier: 'minor', color: '#6fae8a' },
      { id: 'ess', label: { zh: '演化穩定策略', en: 'ESS' }, x: 585, y: 190, tier: 'major', color: '#5f9bc0' },
      { id: 'battleofsexes', label: { zh: '兩性之戰', en: 'Battle of Sexes' }, x: 620, y: 300, tier: 'minor', color: '#5f9bc0' },
      { id: 'parentoffspring', label: { zh: '親子衝突', en: 'Parent–Offspring' }, x: 260, y: 400, tier: 'minor', color: '#5f9bc0' },
      { id: 'familyplanning', label: { zh: '家庭計畫', en: 'Family Planning' }, x: 140, y: 350, tier: 'minor', color: '#5f9bc0' },
      { id: 'meme', label: { zh: '迷因', en: 'Meme' }, x: 655, y: 110, tier: 'lead', color: '#c2a86a' },
      { id: 'extendedphenotype', label: { zh: '延伸的表現型', en: 'Extended Phenotype' }, x: 660, y: 405, tier: 'major', color: '#c2a86a' }
    ],
    edges: [
      { from: 'selfishgene', to: 'replicator', kind: 'family' },
      { from: 'selfishgene', to: 'survivalmachine', kind: 'family' },
      { from: 'selfishgene', to: 'altruism', kind: 'family' },
      { from: 'selfishgene', to: 'extendedphenotype', kind: 'family' },
      { from: 'altruism', to: 'kinselection', kind: 'family' },
      { from: 'altruism', to: 'reciprocal', kind: 'family' },
      { from: 'altruism', to: 'ess', kind: 'family' },
      { from: 'kinselection', to: 'familyplanning', kind: 'family' },
      { from: 'kinselection', to: 'parentoffspring', kind: 'family' },
      { from: 'ess', to: 'battleofsexes', kind: 'family' },
      { from: 'replicator', to: 'meme', kind: 'love' }
    ]
  },
  footer: { quote: { zh: '「在這個星球上，唯有我們，能夠反抗自私複製者的暴政。」', en: '“We, alone on earth, can rebel against the tyranny of the selfish replicators.”' }, tagline: { zh: '自私的基因 · 沉浸式閱讀 · 從基因的視角重看生命', en: 'The Selfish Gene · Immersive Reading · life seen from the gene’s-eye view' } }
};

const CHAPTERS = [
  { id: 1,  group: { zh: '卷一 · 基因的視角', en: 'Part I · The Gene’s-Eye View' }, title: { zh: '為什麼有人？', en: 'Why Are People?' }, reflectQ: { zh: '道金斯說我們「生來自私」，所以更要刻意教導慷慨。你認同「善良需要後天學習」嗎？', en: 'Dawkins says we are "born selfish," so we must deliberately teach generosity. Do you agree that kindness must be learned?' } },
  { id: 2,  group: { zh: '卷一 · 基因的視角', en: 'Part I · The Gene’s-Eye View' }, title: { zh: '複製者', en: 'The Replicators' }, reflectQ: { zh: '生命始於一個會複製自己的分子。「能被複製」為何比「活著」更接近演化的核心？', en: 'Life began with a molecule that copied itself. Why is "being copied" closer to the heart of evolution than "being alive"?' } },
  { id: 3,  group: { zh: '卷一 · 基因的視角', en: 'Part I · The Gene’s-Eye View' }, title: { zh: '不朽的雙螺旋', en: 'Immortal Coils' }, reflectQ: { zh: '個體必死，基因卻近乎不朽。為什麼道金斯主張天擇的單位是「基因」而不是「個體」？', en: 'Individuals die, but genes are near-immortal. Why does Dawkins argue the unit of selection is the gene, not the individual?' } },
  { id: 4,  group: { zh: '卷一 · 基因的視角', en: 'Part I · The Gene’s-Eye View' }, title: { zh: '基因機器', en: 'The Gene Machine' }, reflectQ: { zh: '基因無法即時遙控行為，只能替生存機器裝上大腦與「經驗法則」。這對「自由意志」有什麼暗示？', en: 'Genes cannot micromanage behaviour in real time; they equip survival machines with brains and rules of thumb. What does that imply for "free will"?' } },
  { id: 5,  group: { zh: '卷二 · 自私與利他', en: 'Part II · Selfishness and Altruism' }, title: { zh: '攻擊行為：穩定與自私的機器', en: 'Aggression: Stability and the Selfish Machine' }, reflectQ: { zh: '動物為何不總是拚死鬥爭？「演化穩定策略」為何強調的是穩定，而不是「對物種最好」？', en: 'Why don’t animals always fight to the death? Why does the ESS stress stability rather than "what’s best for the species"?' } },
  { id: 6,  group: { zh: '卷二 · 自私與利他', en: 'Part II · Selfishness and Altruism' }, title: { zh: '基因的算計', en: 'Genesmanship' }, reflectQ: { zh: '親屬選擇：基因會照顧「在親人體內的自己」。這如何從「自私基因」推出對血親的利他？', en: 'Kin selection: a gene looks after copies of itself in relatives. How does altruism toward kin follow from a selfish gene?' } },
  { id: 7,  group: { zh: '卷二 · 自私與利他', en: 'Part II · Selfishness and Altruism' }, title: { zh: '家庭計畫', en: 'Family Planning' }, reflectQ: { zh: '動物節制生育，不是為族群犧牲，而是自身的最適策略。「生」與「養」該如何取捨？', en: 'Animals limit their broods not to sacrifice for the group but as their own optimal strategy. How to weigh "bearing" against "caring"?' } },
  { id: 8,  group: { zh: '卷二 · 自私與利他', en: 'Part II · Selfishness and Altruism' }, title: { zh: '世代之戰', en: 'Battle of the Generations' }, reflectQ: { zh: '親子之間也有衝突：每個孩子都想要比父母「最適分配」更多。你在自己的家庭裡看過這種拉鋸嗎？', en: 'Parent and offspring conflict: each child wants more than the parent optimally gives. Have you seen this tug-of-war in your own family?' } },
  { id: 9,  group: { zh: '卷二 · 自私與利他', en: 'Part II · Selfishness and Altruism' }, title: { zh: '兩性之戰', en: 'Battle of the Sexes' }, reflectQ: { zh: '卵大精子小的不對稱，如何演化出「挑剔的雌性」與各種求偶策略？這對人類有多少解釋力？', en: 'How does the asymmetry of big eggs and tiny sperm evolve "choosy females" and rival courtship strategies — and how far does it explain humans?' } },
  { id: 10, group: { zh: '卷二 · 自私與利他', en: 'Part II · Selfishness and Altruism' }, title: { zh: '你幫我抓背，我搭你便車', en: 'You Scratch My Back, I’ll Ride on Yours' }, reflectQ: { zh: '互惠利他：非親屬之間「你幫我、我幫你」也能演化。它為何需要「記憶」與「辨認個體」？', en: 'Reciprocal altruism can evolve even among non-kin. Why does it require memory and the ability to recognize individuals?' } },
  { id: 11, group: { zh: '卷三 · 超越基因', en: 'Part III · Beyond the Gene' }, title: { zh: '迷因：新的複製者', en: 'Memes: The New Replicators' }, reflectQ: { zh: '觀念、旋律、口號像基因一樣在大腦間複製擴散。你今天腦中揮之不去的「迷因」是哪一個？', en: 'Ideas, tunes, and slogans replicate from brain to brain like genes. Which "meme" is stuck in your head today?' } },
  { id: 12, group: { zh: '卷三 · 超越基因', en: 'Part III · Beyond the Gene' }, title: { zh: '好人出頭天', en: 'Nice Guys Finish First' }, reflectQ: { zh: '重複賽局中，「以牙還牙」——善良、報復、寬恕——竟能勝出。合作為何能從自私中長出來？', en: 'In repeated games, Tit-for-Tat — nice, retaliatory, forgiving — wins. How does cooperation grow out of selfishness?' } },
  { id: 13, group: { zh: '卷三 · 超越基因', en: 'Part III · Beyond the Gene' }, title: { zh: '基因的長臂', en: 'The Long Reach of the Gene' }, reflectQ: { zh: '海狸的水壩、寄生蟲操縱的宿主——基因的效應伸到了體外。「延伸的表現型」把基因視角推到多遠？', en: 'Beaver dams, hosts manipulated by parasites — a gene’s effects reach beyond its own body. How far does the "extended phenotype" push the gene’s-eye view?' } }
];

const CHARACTERS = [
  { id: 'selfishgene', name: { zh: '自私的基因', en: 'The Selfish Gene' }, family: 'gene', role: { zh: '本書的核心論點', en: 'the book’s central thesis' }, icon: '🧬', color: '#4fb89a',
    desc: { zh: '天擇真正作用的單位是「基因」；那些能讓自己更成功地被複製下去的基因，就會勝出、擴散。', en: 'The true unit on which natural selection acts is the gene; genes that get themselves copied more successfully win and spread.' },
    analysis: { zh: '這是全書的視角革命。把演化的主角從「個體」或「物種」換成「基因」，許多謎題就迎刃而解。所謂「自私」是比喻——不是說基因有意識或惡意，而是描述一種傾向：凡是能促使自身拷貝增加的基因，就會在基因庫中勝出。看似利他的行為，底層往往是基因在為「自己的拷貝」精打細算。（第 1、3 章）', en: 'This is the book’s revolution of perspective. Swap the protagonist of evolution from the individual or species to the gene, and many puzzles dissolve. "Selfish" is a metaphor — genes have no mind or malice; it merely names a tendency: any gene that increases its own copies wins in the gene pool. Behaviour that looks altruistic is often genes calculating for their own copies. (Ch. 1, 3)' },
    tags: [ { zh: '天擇單位', en: 'unit of selection' }, { zh: '基因視角', en: 'gene’s-eye view' }, { zh: '比喻的自私', en: 'metaphorical selfishness' } ], related: ['replicator', 'survivalmachine', 'altruism'] },
  { id: 'replicator', name: { zh: '複製者', en: 'The Replicator' }, family: 'gene', role: { zh: '生命的起點', en: 'the origin of life' }, icon: '🌀', color: '#4fb89a',
    desc: { zh: '能夠複製自己的分子。生命的故事，始於原始濃湯裡第一個會自我複製的東西。', en: 'A molecule that makes copies of itself. The story of life begins with the first self-replicating thing in the primeval soup.' },
    analysis: { zh: '道金斯把演化的起點追溯到「複製者」：一旦出現能自我複製、且複製會有微小差錯的分子，天擇就自動開始運作。壽命長、繁殖快、複製精準的複製者勝出，並在漫長競爭中，逐漸打造出保護自己的載具——也就是生存機器。基因，就是今日最成功的複製者。（第 2 章）', en: 'Dawkins traces evolution back to the "replicator": once a molecule can copy itself with occasional errors, natural selection switches on automatically. Replicators with greater longevity, fecundity, and copying-fidelity win, and over vast competition build vehicles to protect themselves — survival machines. The gene is today’s most successful replicator. (Ch. 2)' },
    tags: [ { zh: '自我複製', en: 'self-copying' }, { zh: '原始濃湯', en: 'primeval soup' }, { zh: '長壽/多產/精準', en: 'longevity/fecundity/fidelity' } ], related: ['selfishgene', 'meme'] },
  { id: 'survivalmachine', name: { zh: '生存機器', en: 'The Survival Machine' }, family: 'gene', role: { zh: '基因的載具', en: 'the gene’s vehicle' }, icon: '🤖', color: '#4fb89a',
    desc: { zh: '所有生物的身體，都是基因為了保護、傳遞自己而打造並駕駛的「機器人載具」。', en: 'Every living body is a robot vehicle that genes build and drive to protect and pass on themselves.' },
    analysis: { zh: '這是本書最令人難忘的意象：你我、大象、細菌，都是基因的生存機器。基因無法直接、即時地遙控行為（神經訊號有時間差），於是牠們的策略是打造大腦，給它「經驗法則」與模擬預測未來的能力，讓機器能自行應變。行為，因此是基因遠距下注的結果。（第 4 章）', en: 'The book’s most memorable image: you and I, elephants, bacteria — all survival machines for genes. Genes cannot control behaviour directly and in real time (nerve signals lag), so their strategy is to build brains, equip them with rules of thumb and the power to simulate the future, and let the machine cope on its own. Behaviour is thus a gene’s bet placed at a distance. (Ch. 4)' },
    tags: [ { zh: '載具', en: 'vehicle' }, { zh: '大腦', en: 'brain' }, { zh: '經驗法則', en: 'rules of thumb' } ], related: ['selfishgene', 'replicator'] },
  { id: 'altruism', name: { zh: '利他行為', en: 'Altruism' }, family: 'behavior', role: { zh: '從自私中演化出的無私', en: 'selflessness evolved from selfishness' }, icon: '🤝', color: '#6fae8a',
    desc: { zh: '一個個體犧牲自己、造福他者的行為。本書的核心謎題：自私的基因，怎麼會產生利他？', en: 'Behaviour in which one individual sacrifices for another. The book’s central puzzle: how can selfish genes produce altruism?' },
    analysis: { zh: '道金斯的答案優雅而顛覆：利他不必靠「為群體犧牲」，而是自私基因的副產品。當受益者體內帶有同一基因的拷貝（親屬選擇），或當幫助能換來日後回報（互惠利他），一個「促使個體利他」的基因反而能讓自身拷貝增加。無私，就這樣從自私裡長了出來。（第 6、10 章）', en: 'Dawkins’s answer is elegant and subversive: altruism need not rest on "sacrifice for the group" but is a by-product of selfish genes. When the beneficiary carries copies of the same gene (kin selection), or when help earns later return (reciprocal altruism), a gene that makes its bearer altruistic can actually increase its own copies. Selflessness grows out of selfishness. (Ch. 6, 10)' },
    tags: [ { zh: '親屬選擇', en: 'kin selection' }, { zh: '互惠', en: 'reciprocity' }, { zh: '非為群體', en: 'not for the group' } ], related: ['kinselection', 'reciprocal', 'ess'] },
  { id: 'kinselection', name: { zh: '親屬選擇', en: 'Kin Selection' }, family: 'behavior', role: { zh: '照顧「體內的自己」', en: 'caring for copies of oneself' }, icon: '👨‍👩‍👧', color: '#6fae8a',
    desc: { zh: '基因會「幫助」在親屬體內的自身拷貝；血緣越近、代價越低、利益越大，就越值得利他。', en: 'A gene helps copies of itself in relatives; the closer the kin, the lower the cost, and the greater the benefit, the more altruism pays.' },
    analysis: { zh: '漢彌爾頓的洞見（本書的理論支柱之一）：一個讓你照顧兄弟姊妹、子女的基因，其實是在照顧「另一副身體裡的自己」。用親緣係數 r 與代價/利益一衡量，就能預測利他該給誰、給多少（內含適應度）。這解釋了從螞蟻的犧牲到父母的舐犢之情。（第 6 章）', en: 'Hamilton’s insight (a theoretical pillar of the book): a gene that makes you care for siblings or children is really caring for copies of itself in other bodies. Weigh relatedness r against cost and benefit, and you can predict to whom and how much altruism should flow (inclusive fitness). It explains everything from a sterile ant’s sacrifice to a parent’s devotion. (Ch. 6)' },
    tags: [ { zh: '漢彌爾頓法則', en: 'Hamilton’s rule' }, { zh: '親緣係數', en: 'relatedness' }, { zh: '內含適應度', en: 'inclusive fitness' } ], related: ['altruism', 'familyplanning', 'parentoffspring'] },
  { id: 'reciprocal', name: { zh: '互惠利他', en: 'Reciprocal Altruism' }, family: 'behavior', role: { zh: '你幫我，我幫你', en: 'you scratch my back' }, icon: '🔁', color: '#6fae8a',
    desc: { zh: '沒有血緣的個體之間，「延遲回報」式的互相幫忙，也能在演化中站得住腳。', en: 'Even among non-kin, delayed "help-for-help" can be evolutionarily stable.' },
    analysis: { zh: '互惠利他（特里弗斯）要能運作，需要幾個條件：個體會重複相遇、壽命夠長、且能「認得對方、記得誰回報過、誰是騙子」。清潔魚為大魚清理、大魚也不吃牠；吸血蝙蝠會把血食分給當晚沒吃到的同伴。這也為後面「重複賽局中的合作」鋪好了路。（第 10、12 章）', en: 'For reciprocal altruism (Trivers) to work, several conditions are needed: individuals must meet repeatedly, live long enough, and be able to recognize others and remember who reciprocated and who cheated. Cleaner fish groom big fish and are spared; vampire bats share blood with comrades who missed a meal. This paves the way for cooperation in repeated games. (Ch. 10, 12)' },
    tags: [ { zh: '延遲回報', en: 'delayed return' }, { zh: '辨認個體', en: 'individual recognition' }, { zh: '防騙子', en: 'cheater detection' } ], related: ['altruism'] },
  { id: 'ess', name: { zh: '演化穩定策略', en: 'Evolutionarily Stable Strategy' }, family: 'behavior', role: { zh: '演化裡的賽局論', en: 'game theory in evolution' }, icon: '♟️', color: '#5f9bc0',
    desc: { zh: 'ESS：一旦族群多數採用、就沒有任何變異策略能入侵取代的策略組合。', en: 'The ESS: a strategy that, once adopted by most of a population, cannot be invaded and displaced by any mutant strategy.' },
    analysis: { zh: '梅納德·史密斯把賽局論帶進演化。以「鷹鴿賽局」為例：全兇的鷹會彼此重創、全溫的鴿會被鷹欺負，於是族群往往停在某個鷹鴿混合的比例——這個比例之所以穩定，不是因為「對物種好」，而是因為任何偏離它的策略都討不到便宜。這是理解動物為何「有所節制」的鑰匙。（第 5 章）', en: 'Maynard Smith brought game theory to evolution. Take the hawk-dove game: all-hawk populations maim each other, all-dove populations get bullied, so the population settles at some hawk-dove mix — stable not because it is "good for the species," but because any deviation does worse. It is the key to why animals show restraint. (Ch. 5)' },
    tags: [ { zh: '鷹鴿賽局', en: 'hawk-dove' }, { zh: '穩定非最優', en: 'stable, not optimal' }, { zh: '賽局論', en: 'game theory' } ], related: ['altruism', 'battleofsexes'] },
  { id: 'battleofsexes', name: { zh: '兩性之戰', en: 'The Battle of the Sexes' }, family: 'behavior', role: { zh: '投資不對稱的後果', en: 'the fallout of unequal investment' }, icon: '⚥', color: '#5f9bc0',
    desc: { zh: '卵大而少、精子小而多，兩性的「投資」從一開始就不對稱，由此演化出不同的性策略。', en: 'Big scarce eggs, tiny plentiful sperm — the sexes invest unequally from the start, and different sexual strategies evolve.' },
    analysis: { zh: '因為母方通常投資更多（大卵、懷孕、育幼），一旦被拋棄損失更大，於是傾向「挑剔」、要求承諾；公方則傾向多交配。由此在演化上拉扯出「羞怯 vs 急躁」「忠貞 vs 濫情」等策略的動態平衡，也是性擇（誇張的雄性裝飾）的來源。（第 9 章）', en: 'Because the female usually invests more (big eggs, gestation, rearing) and loses more if deserted, she tends to be choosy and demand commitment, while the male tends toward many matings. This tugs out an evolutionary balance of strategies — coy vs fast, faithful vs philandering — and is the source of sexual selection (extravagant male ornaments). (Ch. 9)' },
    tags: [ { zh: '親代投資', en: 'parental investment' }, { zh: '性擇', en: 'sexual selection' }, { zh: '策略', en: 'strategies' } ], related: ['ess'] },
  { id: 'parentoffspring', name: { zh: '親子衝突', en: 'Parent–Offspring Conflict' }, family: 'behavior', role: { zh: '血親之間的拉鋸', en: 'a tug-of-war among close kin' }, icon: '🍼', color: '#5f9bc0',
    desc: { zh: '即使基因相同一半，親代與子代的「最適利益」也不一致——每個孩子都想多要一點。', en: 'Even sharing half their genes, parent and offspring have different optima — each child wants a little more than it should get.' },
    analysis: { zh: '特里弗斯指出：父母的基因希望「公平」分配資源給每個孩子與未來的孩子，但每個孩子的基因卻希望「多拿一點」（因為牠和自己的親緣是 1、和手足只有 1/2）。斷奶衝突、手足競爭、幼獸的「情緒勒索」都由此而來——衝突就藏在最親密的關係裡。（第 8 章）', en: 'Trivers showed that a parent’s genes favour a "fair" split of resources among all its children, present and future, while each child’s genes favour grabbing a bit more (it is related to itself by 1, to a sibling by only 1/2). Weaning conflict, sibling rivalry, and a pup’s "emotional blackmail" all follow — conflict hides inside the closest bonds. (Ch. 8)' },
    tags: [ { zh: '斷奶衝突', en: 'weaning conflict' }, { zh: '手足競爭', en: 'sibling rivalry' }, { zh: '最適不一致', en: 'divergent optima' } ], related: ['kinselection'] },
  { id: 'familyplanning', name: { zh: '家庭計畫', en: 'Family Planning' }, family: 'behavior', role: { zh: '生多少才最划算', en: 'how many young pay off' }, icon: '🐣', color: '#5f9bc0',
    desc: { zh: '動物「節制」生育，不是為族群犧牲的美德，而是讓自己傳下最多存活後代的最適策略。', en: 'Animals that limit their broods are not sacrificing for the group; it is the strategy that leaves them the most surviving descendants.' },
    analysis: { zh: '道金斯用這章反駁「為族群好而自我節制」的群體選擇論。鳥類生的蛋數往往剛好是「養得活的最大數」（Lack 的理論）——生太多反而每隻都養不好、總存活數更少。所以看似無私的節育，其實是自私基因的精算：重點不是「生」，而是「養得活幾個」。（第 7 章）', en: 'Dawkins uses this chapter to refute the group-selection idea of "self-restraint for the good of the species." Birds often lay just the number they can actually raise (Lack’s theory) — lay too many and each fares worse, so fewer survive overall. Apparent selfless birth control is really the selfish gene’s arithmetic: what counts is not bearing young but how many you can raise. (Ch. 7)' },
    tags: [ { zh: 'Lack 理論', en: 'Lack’s theory' }, { zh: '生vs養', en: 'bearing vs caring' }, { zh: '反群體選擇', en: 'anti-group-selection' } ], related: ['kinselection'] },
  { id: 'meme', name: { zh: '迷因', en: 'The Meme' }, family: 'beyond', role: { zh: '文化的複製者', en: 'the replicator of culture' }, icon: '💡', color: '#c2a86a',
    desc: { zh: '觀念、旋律、口號、時尚——這些在人腦之間複製、擴散的文化單位，道金斯稱之為「迷因」。', en: 'Ideas, tunes, slogans, fashions — units of culture that copy and spread from brain to brain. Dawkins calls them "memes."' },
    analysis: { zh: '這是本書留給世界的一個新詞。道金斯提出：地球上也許出現了「第二種複製者」——迷因。就像基因藉由從身體跳到身體來繁衍，迷因藉由從大腦跳到大腦（模仿、傳播）來繁衍。好記、好傳、能激起情感的迷因就會勝出，未必因為它「對」或「有益」。這開啟了用演化眼光看文化的一整條路。（第 11 章）', en: 'This is the book’s gift of a new word. Dawkins proposes that a second kind of replicator may have arisen on Earth — the meme. Just as genes propagate by leaping from body to body, memes propagate by leaping from brain to brain (imitation, transmission). Memes that are memorable, transmissible, and emotionally charged win — not necessarily because they are true or beneficial. It opens a whole way of seeing culture through an evolutionary lens. (Ch. 11)' },
    tags: [ { zh: '文化演化', en: 'cultural evolution' }, { zh: '模仿傳播', en: 'imitation' }, { zh: '新的複製者', en: 'a new replicator' } ], related: ['replicator', 'extendedphenotype'] },
  { id: 'extendedphenotype', name: { zh: '延伸的表現型', en: 'The Extended Phenotype' }, family: 'beyond', role: { zh: '基因伸出體外的手', en: 'the gene’s reach beyond the body' }, icon: '🦫', color: '#c2a86a',
    desc: { zh: '基因的效應不限於它所在的身體，還能「伸出去」改變外在世界——甚至改變其他生物的行為。', en: 'A gene’s effects are not confined to its own body; they reach out to shape the outside world — even the behaviour of other organisms.' },
    analysis: { zh: '這是道金斯最大膽、也最鍾愛的推展（另有專書《延伸的表現型》）。海狸築的水壩、石蠶蛾用小石造的巢、寄生蟲操縱宿主自尋死路——這些都不是普通意義的「身體特徵」，卻同樣是基因為了自身複製而造出的「表現型」。基因視角推到極致：所謂的界線（哪裡是身體、哪裡是環境）其實是可以被跨越的。（第 13 章）', en: 'This is Dawkins’s boldest and most cherished extension (with a whole later book, "The Extended Phenotype"). A beaver’s dam, a caddis larva’s stone house, a parasite driving its host to suicide — these are not "bodily traits" in the ordinary sense, yet they are just as much phenotypes built by genes for their own copying. The gene’s-eye view taken to its limit: the boundary between body and world can be crossed. (Ch. 13)' },
    tags: [ { zh: '海狸水壩', en: 'beaver dams' }, { zh: '寄生操縱', en: 'parasite manipulation' }, { zh: '跨越體界', en: 'beyond the body' } ], related: ['selfishgene', 'meme'] }
];

const TIMELINE_DATA = [
  { year: { zh: '1859', en: '1859' }, event: { zh: '達爾文《物種起源》：天擇', en: 'Darwin’s "On the Origin of Species": natural selection' }, novel: { zh: '全書的地基。道金斯要做的，是把天擇的焦點從「個體」精確地移到「基因」。', en: 'The book’s foundation. Dawkins’s task is to move the focus of selection precisely from the individual to the gene.' }, type: 'history' },
  { year: { zh: '1930s', en: '1930s' }, event: { zh: '現代綜合論（族群遺傳學）', en: 'The Modern Synthesis (population genetics)' }, novel: { zh: 'Fisher、Haldane、Wright 把達爾文與孟德爾結合，為「以基因計算演化」鋪好數學基礎。', en: 'Fisher, Haldane, and Wright fused Darwin with Mendel, laying the mathematical basis for reckoning evolution in genes.' }, type: 'history' },
  { year: { zh: '1964', en: '1964' }, event: { zh: '漢彌爾頓：親屬選擇與內含適應度', en: 'Hamilton: kin selection and inclusive fitness' }, novel: { zh: '對應第 6 章。這是全書解釋「利他」最重要的理論支柱。', en: 'Maps to Ch. 6. The single most important pillar for the book’s account of altruism.' }, type: 'character' },
  { year: { zh: '1971–72', en: '1971–72' }, event: { zh: '特里弗斯：互惠利他與親代投資', en: 'Trivers: reciprocal altruism and parental investment' }, novel: { zh: '對應第 8–10 章。為互惠、兩性之戰與親子衝突提供了理論。', en: 'Maps to Ch. 8–10. Supplies the theory for reciprocity, the battle of the sexes, and parent–offspring conflict.' }, type: 'character' },
  { year: { zh: '1973', en: '1973' }, event: { zh: '梅納德·史密斯：演化穩定策略（ESS）', en: 'Maynard Smith: the evolutionarily stable strategy (ESS)' }, novel: { zh: '對應第 5 章。把賽局論帶進演化，解釋動物為何有所節制。', en: 'Maps to Ch. 5. Brings game theory to evolution and explains animal restraint.' }, type: 'character' },
  { year: { zh: '1976', en: '1976' }, event: { zh: '道金斯《自私的基因》出版', en: 'Dawkins publishes "The Selfish Gene"' }, novel: { zh: '你正在讀的這本書。它把上述理論綜合起來，並首創「迷因」一詞。', en: 'The very book you are reading. It synthesizes the above theories and coins the word "meme."' }, type: 'history' },
  { year: { zh: '1982', en: '1982' }, event: { zh: '道金斯《延伸的表現型》', en: 'Dawkins’s "The Extended Phenotype"' }, novel: { zh: '對應第 13 章。他把「基因視角」推到體界之外，這是他自認最重要的貢獻。', en: 'Maps to Ch. 13. He pushes the gene’s-eye view beyond the body — the contribution he regards as his most important.' }, type: 'history' },
  { year: { zh: '1989', en: '1989' }, event: { zh: '第二版增補第 12、13 章', en: 'The 2nd edition adds chapters 12 and 13' }, novel: { zh: '「好人出頭天」（重複賽局中的合作）與「基因的長臂」（延伸的表現型）加入本書。', en: '"Nice Guys Finish First" (cooperation in repeated games) and "The Long Reach of the Gene" join the book.' }, type: 'history' },
  { year: { zh: '2006 / 2016', en: '2006 / 2016' }, event: { zh: '三十／四十週年紀念版', en: '30th and 40th anniversary editions' }, novel: { zh: '出版數十年後，本書仍在重印與再版——它本身就成了一個極成功的「迷因」。', en: 'Decades on, the book is still reprinted and re-edited — it has itself become a wildly successful "meme."' }, type: 'history' }
];

const THEMES = [
  { id: 'geneseye', icon: '🧬', title: { zh: '基因的視角', en: 'The Gene’s-Eye View' }, subtitle: { zh: '把演化的主角換一個', en: 'swapping the protagonist of evolution' }, color: '#4fb89a',
    intro: { zh: '全書的視角革命：天擇真正的單位，是基因，不是個體或物種。', en: 'The book’s revolution of perspective: the true unit of selection is the gene, not the individual or the species.' },
    body: { zh: '<p>過去我們習慣問「這對個體／物種有什麼好處」，道金斯要我們改問「這對基因有什麼好處」。因為基因才是那個能跨越世代、近乎不朽的複製者；個體與身體只是它短暫的載具。</p><p>只要換上這副「基因的眼睛」，許多原本費解的行為——犧牲、節育、性別差異——都會忽然說得通。這是一種思考工具，也是一場思想上的哥白尼革命。</p><div class="theme-quote">「基因就在你我體內；牠們創造了我們的身與心，而保存牠們，正是我們存在的終極理由。」</div>', en: '<p>We used to ask "what good is this for the individual or the species?" Dawkins asks instead "what good is this for the gene?" — because the gene is the near-immortal replicator that crosses generations, while individuals and bodies are its transient vehicles.</p><p>Put on these "gene’s eyes" and much puzzling behaviour — sacrifice, birth control, sex differences — suddenly makes sense. It is a thinking tool, and a Copernican shift of viewpoint.</p><div class="theme-quote">“They are in you and in me; they created us, body and mind; and their preservation is the ultimate rationale for our existence.”</div>' },
    chapters: ['1', '2', '3', '4'] },
  { id: 'machine', icon: '🤖', title: { zh: '生存機器', en: 'Survival Machines' }, subtitle: { zh: '我們只是基因的載具', en: 'we are the gene’s vehicles' }, color: '#4fb89a',
    intro: { zh: '你我、大象、細菌，都是基因為了複製自己而打造、駕駛的機器人。', en: 'You and I, elephants, bacteria — all robots the gene builds and drives to copy itself.' },
    body: { zh: '<p>基因無法即時遙控行為，於是牠的策略是打造大腦、給它經驗法則與預測能力，讓生存機器自己臨機應變。這個意象既冷峻又解放：我們的身體是工具，但駕駛座上，還有能思考、能反抗的「我們」。</p><div class="theme-quote">「我們是生存機器——被盲目編程來保存基因這種自私分子的機器人載具。」</div>', en: '<p>Genes cannot micromanage behaviour in real time, so their strategy is to build brains, equip them with rules of thumb and foresight, and let the survival machine improvise. The image is both bleak and liberating: our bodies are tools, yet in the driver’s seat sits a "we" that can think — and rebel.</p><div class="theme-quote">“We are survival machines — robot vehicles blindly programmed to preserve the selfish molecules known as genes.”</div>' },
    chapters: ['4', '3'] },
  { id: 'altruism', icon: '🤝', title: { zh: '利他的演化', en: 'The Evolution of Altruism' }, subtitle: { zh: '無私如何從自私長出來', en: 'how selflessness grows from selfishness' }, color: '#6fae8a',
    intro: { zh: '本書最深刻的謎題：自私的基因，怎麼會產生真實的利他行為？', en: 'The book’s deepest puzzle: how do selfish genes produce genuine altruistic behaviour?' },
    body: { zh: '<p>答案有兩條主線。其一是親屬選擇：幫助血親，等於在照顧「另一副身體裡的自己」。其二是互惠利他：只要能重複相遇、記得誰回報過，「你幫我、我幫你」就能站得住腳。</p><p>關鍵在於：這裡不需要「為群體犧牲」的高尚假設。利他是自私基因精算後的結果——這既讓利他失去了一部分神聖光環，卻也讓它有了堅實的演化根基。</p><div class="theme-quote">「讓我們試著教導慷慨與利他吧，因為我們生來自私。」</div>', en: '<p>There are two main strands. One is kin selection: helping relatives is caring for copies of yourself in other bodies. The other is reciprocal altruism: given repeated encounters and memory of who reciprocated, "you help me, I help you" holds up.</p><p>Crucially, no noble assumption of "sacrifice for the group" is needed. Altruism is the calculated result of selfish genes — which strips it of some of its halo, yet gives it a solid evolutionary footing.</p><div class="theme-quote">“Let us try to teach generosity and altruism, because we are born selfish.”</div>' },
    chapters: ['6', '10', '7', '8'] },
  { id: 'ess', icon: '♟️', title: { zh: '演化穩定策略', en: 'The Evolutionarily Stable Strategy' }, subtitle: { zh: '演化裡的賽局論', en: 'game theory in evolution' }, color: '#5f9bc0',
    intro: { zh: '動物之間的「有所節制」，不是為了物種好，而是策略上的穩定均衡。', en: 'The restraint animals show is not for the good of the species, but a stable strategic equilibrium.' },
    body: { zh: '<p>梅納德·史密斯的 ESS 把賽局論帶進演化：一個策略之所以能長存，是因為當多數人都採用它時，沒有任何變異策略能入侵得逞。鷹鴿賽局說明了為何純粹的兇狠或純粹的溫和都不穩定，族群往往停在某個混合比例。</p><p>這個概念也貫穿了兩性之戰、親子衝突——凡是有利益衝突之處，就有 ESS 在暗中決定平衡點。</p><div class="theme-quote">「穩定的，未必是對大家最好的；只是沒有人能靠背離它而佔到便宜。」</div>', en: '<p>Maynard Smith’s ESS brings game theory to evolution: a strategy endures because, once most adopt it, no mutant strategy can successfully invade. The hawk-dove game shows why pure aggression or pure meekness is unstable, and populations settle at some mix.</p><p>The idea runs through the battle of the sexes and parent–offspring conflict too — wherever interests clash, an ESS quietly fixes the balance point.</p><div class="theme-quote">“What is stable need not be best for all; it is only that no one gains by deviating from it.”</div>' },
    chapters: ['5', '9', '8'] },
  { id: 'meme', icon: '💡', title: { zh: '迷因', en: 'The Meme' }, subtitle: { zh: '文化也有它的複製者', en: 'culture has its replicator too' }, color: '#c2a86a',
    intro: { zh: '道金斯留給世界的新詞：在基因之外，文化也演化出了自己的複製者。', en: 'Dawkins’s gift of a new word: beyond genes, culture has evolved its own replicator.' },
    body: { zh: '<p>觀念、旋律、口號、信仰，像基因一樣藉由「從一個大腦跳到另一個大腦」來繁衍。好記、好傳、能激起情感的迷因就會勝出——未必因為它為真或有益。</p><p>這開啟了用演化眼光看文化的一整條路，也讓道金斯得以在結尾提出全書最有人味的希望：我們是唯一能反抗複製者暴政的物種。</p><div class="theme-quote">「迷因藉由從一個大腦跳到另一個大腦，在迷因庫中繁衍。」</div>', en: '<p>Ideas, tunes, slogans, and beliefs propagate like genes, by leaping from brain to brain. Memes that are memorable, transmissible, and emotionally charged win — not necessarily because they are true or good.</p><p>This opens a whole way of viewing culture through evolution, and lets Dawkins end with the book’s most human note of hope: we are the only species that can rebel against the tyranny of the replicators.</p><div class="theme-quote">“Memes propagate themselves in the meme pool by leaping from brain to brain.”</div>' },
    chapters: ['11', '13'] },
  { id: 'extended', icon: '🦫', title: { zh: '延伸的表現型', en: 'The Extended Phenotype' }, subtitle: { zh: '基因伸出體外的手', en: 'the gene’s reach beyond the body' }, color: '#c2a86a',
    intro: { zh: '基因的效應不止於身體之內——它伸得出去，甚至能操縱別的生物。', en: 'A gene’s effects do not stop at the body — they reach out, even manipulating other organisms.' },
    body: { zh: '<p>海狸的水壩、石蠶蛾用小石造的巢、寄生蟲驅使宿主自尋死路——這些都不是傳統意義的身體特徵，卻同樣是基因為了複製自己而造出的「表現型」。</p><p>這是「基因視角」的終極推展：所謂身體與環境的界線，其實是可以被基因跨越的。全書至此，把一開始那個看似狹隘的「自私基因」，推展成了一種看待整個生命世界的宏大方式。</p><div class="theme-quote">「基因的力量，能伸到牠所在的身體之外。」</div>', en: '<p>A beaver’s dam, a caddis larva’s stone house, a parasite driving its host to suicide — none are bodily traits in the usual sense, yet all are phenotypes built by genes for their own copying.</p><p>This is the gene’s-eye view taken to its limit: the boundary between body and world can be crossed by the gene. By here, the book has grown that seemingly narrow "selfish gene" into a grand way of seeing the whole living world.</p><div class="theme-quote">“The power of a gene reaches beyond the body in which it sits.”</div>' },
    chapters: ['13', '11'] }
];

const QUOTES = [
  { text: { zh: '我們是生存機器——被盲目編程來保存基因這種自私分子的機器人載具。', en: 'We are survival machines — robot vehicles blindly programmed to preserve the selfish molecules known as genes.' }, source: { zh: '第 2 章', en: 'Chapter 2' },
    analysis: { zh: '全書最著名、也最令人震動的一句。它一舉把「主角」從我們身上奪走，交給了基因；但道金斯的用意不是要人消沉，而是先看清真相，才談得上超越它。', en: 'The book’s most famous and jarring line. In one stroke it takes the "protagonist" away from us and hands it to the gene. Dawkins’s point is not to depress us but to see the truth clearly first — only then can we rise above it.' } },
  { text: { zh: '牠們就在你我體內；牠們創造了我們的身與心，而保存牠們，正是我們存在的終極理由。', en: 'They are in you and in me; they created us, body and mind; and their preservation is the ultimate rationale for our existence.' }, source: { zh: '第 2 章', en: 'Chapter 2' },
    analysis: { zh: '把「基因視角」講到極致的一句。它冷靜、甚至冷酷，卻是理解全書的鑰匙：一旦接受「我們是為基因而存在」，後面所有關於利他與衝突的解釋才立得起來。', en: 'The gene’s-eye view pushed to its extreme. Cool, even cold, yet it is the key to the book: once you accept that "we exist for the genes," all that follows about altruism and conflict stands on firm ground.' } },
  { text: { zh: '讓我們試著教導慷慨與利他吧，因為我們生來自私。', en: 'Let us try to teach generosity and altruism, because we are born selfish.' }, source: { zh: '第 1 章', en: 'Chapter 1' },
    analysis: { zh: '常被誤讀為「叫人自私」的反面。道金斯其實在說：正因為天性偏向自私，善良才更需要被有意識地教導與選擇——這也預告了全書結尾「反抗複製者」的立場。', en: 'Often misread as the opposite of what it says. Dawkins’s point: precisely because our nature leans selfish, kindness must be consciously taught and chosen — foreshadowing the book’s closing call to "rebel against the replicators."' } },
  { text: { zh: '一個成功的基因，可預期會有的突出特質，就是無情的自私。', en: 'A predominant quality to be expected in a successful gene is ruthless selfishness.' }, source: { zh: '第 1 章', en: 'Chapter 1' },
    analysis: { zh: '這裡的「自私」是嚴格的技術定義：指基因傾向於做出讓「自己被複製」的事，與心理上的自私無關。分清這一點，才不會把整本書讀歪。', en: 'Here "selfishness" is a strict technical term: a gene’s tendency to do what gets itself copied, unrelated to psychological selfishness. Keep this straight and you won’t misread the whole book.' } },
  { text: { zh: '迷因藉由從一個大腦跳到另一個大腦，在迷因庫中繁衍。', en: 'Memes propagate themselves in the meme pool by leaping from brain to brain.' }, source: { zh: '第 11 章', en: 'Chapter 11' },
    analysis: { zh: '「迷因」概念的原始定義。道金斯大膽提出：地球上或許已出現第二種複製者——文化。這個詞本身也成了史上最成功的迷因之一。', en: 'The original definition of the "meme." Dawkins boldly proposes a second replicator may have arisen on Earth — culture. The word itself has become one of history’s most successful memes.' } },
  { text: { zh: '在這個星球上，唯有我們，能夠反抗自私複製者的暴政。', en: 'We, alone on earth, can rebel against the tyranny of the selfish replicators.' }, source: { zh: '第 11 章 · 結語', en: 'Chapter 11 · closing' },
    analysis: { zh: '全書最有人味、也最鼓舞人心的一句。承認被基因與迷因塑造，不等於任其擺布：人類有能力用意識與文化，做出違背基因短視利益的選擇。這是道金斯留下的自由火光。', en: 'The book’s most human and uplifting line. To admit we are shaped by genes and memes is not to be at their mercy: humans can use consciousness and culture to choose against the genes’ short-sighted interests. It is the spark of freedom Dawkins leaves us.' } },
  { text: { zh: '基因的力量，能伸到牠所在的身體之外。', en: 'The power of a gene reaches beyond the body in which it sits.' }, source: { zh: '第 13 章 · 延伸的表現型', en: 'Chapter 13 · the extended phenotype' },
    analysis: { zh: '「延伸的表現型」的核心。海狸的水壩、蜘蛛的網、寄生蟲操縱的宿主，都是基因效應伸出體外的證據。它把基因視角推到最遠，也最能展現道金斯思想的膽識。', en: 'The heart of the "extended phenotype." A beaver’s dam, a spider’s web, a manipulated host — all are a gene’s effects reaching beyond its body. It pushes the gene’s-eye view furthest, and best shows the daring of Dawkins’s thought.' } }
];

const REFLECTION_QUESTIONS = [
  { zh: '把「這對個體好不好」改成「這對基因好不好」，你能重新解釋哪一種你原本覺得很奇怪的動物（或人類）行為？', en: 'Swap "is this good for the individual?" for "is this good for the gene?" — which puzzling animal (or human) behaviour can you now re-explain?' },
  { zh: '「我們是基因的生存機器」——這個說法讓你感到被貶低，還是被解放？為什麼？', en: '"We are survival machines for our genes." Does that feel belittling, or liberating? Why?' },
  { zh: '道金斯說利他多半是自私基因的精算。這會不會讓「善良」失去意義？還是反而讓它更珍貴？', en: 'Dawkins says altruism is mostly the selfish gene’s arithmetic. Does that drain "kindness" of meaning — or make it more precious?' },
  { zh: '親屬選擇解釋了我們為何偏愛血親。你覺得這對「大愛」「四海之內皆兄弟」是支持還是挑戰？', en: 'Kin selection explains why we favour blood relatives. Does that support or challenge the ideal of universal love?' },
  { zh: '想一個你最近幫忙別人的例子。用「親屬選擇／互惠利他」拆解，它裡面有多少「回報的期待」？', en: 'Think of a time you recently helped someone. Break it down by kin selection / reciprocity — how much "expectation of return" was in it?' },
  { zh: '「穩定的策略未必是對大家最好的。」你在職場、社會或國際關係裡，見過這種 ESS 式的僵局嗎？', en: 'A stable strategy need not be best for all. Have you seen this kind of ESS deadlock at work, in society, or between nations?' },
  { zh: '此刻正在你腦中「繁衍」的迷因是哪一個？它是靠「為真」還是靠「好傳、能勾起情緒」而擴散的？', en: 'Which meme is "reproducing" in your head right now? Does it spread by being true, or by being catchy and emotive?' },
  { zh: '如果人類是唯一能「反抗自私複製者」的物種，你自己最想反抗基因或迷因的哪一個短視傾向？', en: 'If humans alone can "rebel against the selfish replicators," which short-sighted pull of a gene or a meme do you most want to resist?' },
  { zh: '「延伸的表現型」說基因能影響體外世界。人類的科技、城市、網路，算不算我們基因（或迷因）的延伸表現型？', en: 'The "extended phenotype" says genes shape the world beyond the body. Are human technology, cities, and the internet extended phenotypes of our genes (or memes)?' },
  { zh: '讀完後，你會用「自私」還是「合作」來形容生命的本質？或者這本書正是要說：兩者其實是同一件事？', en: 'After reading, would you call life’s essence "selfish" or "cooperative"? Or is the book’s point that they are the same thing?' }
];

const CHAPTER_CONTENT = {};
Object.assign(CHAPTER_CONTENT, {
  1: {
    num: { zh: '第 1 章', en: 'Chapter 1' },
    title: { zh: '為什麼有人？', en: 'Why Are People?' },
    epigraph: {
      zh: '「我們是被打造出來的機器，任務是替我們體內那些自私的基因效勞。」',
      en: '“We are built to serve the tiny replicators that ride inside us.”'
    },
    body: {
      zh: `<p><strong>核心論點：</strong>本章是全書的預告。道金斯提出一個看似冷峻的主張：包括人類在內的一切生命，本質上都是基因為了讓自己被複製而打造出來的「生存機器 (survival machine)」。要真正理解自私與利他這類行為，不能停在個體或物種的層次，而要下降到「基因」這個天擇真正作用的單位，改用「基因視角 (gene's-eye view)」來看世界。</p><p><strong>論證：</strong>他先掃除兩個常見誤區。其一，把演化說成「為了物種好」是模糊而錯誤的，因為天擇並不會為了群體的長遠利益而運作。其二，道德不能從演化「應該如何」直接讀出——他描述基因是「自私的」，是在做科學描述，不是在替自私背書。正因為天生的傾向偏向自利，他反而主張：慷慨與利他必須靠後天刻意教導，別指望它會從我們的生物本性裡自動長出來。</p><div class="section-break">◆ ◆ ◆</div><p><strong>關鍵實例：</strong>「自私的基因」這個書名本身就是最好的例子，也最容易被誤讀。這裡的「自私」是一種比喻：基因沒有意圖、沒有慾望，它不會盤算什麼。所謂「自私」，只是指那些傾向讓自己被更多地複製下去的基因，會在世代競爭中勝出、留存下來——彷彿它「只顧自己」。單位是基因，被描述的是統計上的傾向，而非道德意志。</p><p><strong>啟示：</strong>換個層次看問題，答案會完全不同。當你不再問「這對個體或物種有什麼好處」，改問「這對負責製造這個行為的基因有什麼好處」，許多原本矛盾的生物現象會忽然說得通。這正是全書要反覆示範的思維工具。</p><p class="thought-question">🤔 思考：如果我們天生就被寫入了自利的傾向，那麼你所珍視的慷慨與善意，究竟是天性，還是一種需要世代守護、隨時可能鬆手的後天成就？</p>`,
      en: `<p><strong>Core claim:</strong> This chapter is a trailer for the whole book. Dawkins advances a bracing thesis: all living things, humans included, are essentially "survival machines" that genes have built so those genes can go on being copied. To understand behaviors like selfishness and altruism, you must stop at neither the individual nor the species, but descend to the gene, the level where natural selection truly bites, and adopt the gene's-eye view of the living world.</p><p><strong>The argument:</strong> He first clears away two common errors. One: explaining evolution as being "for the good of the species" is vague and wrong, because selection does not work toward a group's long-term welfare. Two: you cannot read morality off what evolution "should" do. Calling genes selfish is a scientific description, not an endorsement. In fact, precisely because our innate leanings tilt toward self-interest, he argues that generosity and altruism must be deliberately taught. Do not expect them to sprout on their own from our biology.</p><div class="section-break">◆ ◆ ◆</div><p><strong>Key example:</strong> The title itself is the best example, and the easiest to misread. "Selfish" here is a metaphor. A gene has no intentions and no desires; it schemes nothing. To say a gene is selfish means only that genes which tend to get themselves copied more often will win out across generations and persist, as if each were "looking out for itself." The unit is the gene, and what is described is a statistical tendency, not a moral will.</p><p><strong>Takeaway:</strong> Shift the level of the question and the answer changes completely. Stop asking what benefits the individual or the species, and start asking what benefits the gene responsible for building the behavior. Many puzzling biological facts suddenly make sense. This is the thinking tool the book will demonstrate again and again.</p><p class="thought-question">🤔 Reflect: If self-interest is written into us from birth, is the generosity you value a natural gift, or a fragile cultural achievement that each generation must consciously guard and could always let slip?</p>`
    }
  },
  2: {
    num: { zh: '第 2 章', en: 'Chapter 2' },
    title: { zh: '複製者', en: 'The Replicators' },
    epigraph: {
      zh: '「生命的起點，是一個懂得複製自己的分子。」',
      en: '“Life began with a molecule that learned to make copies of itself.”'
    },
    body: {
      zh: `<p><strong>核心論點：</strong>本章追溯生命的最初源頭。道金斯設想在遠古地球的「原始濃湯」裡，偶然出現了第一個能夠複製自己的分子——他稱之為「複製者 (replicator)」。生命的故事，本質上就是複製者之間為了被更多地複製而展開的競爭史。</p><p><strong>論證：</strong>一旦出現能自我拷貝的分子，指數式的增殖就會啟動；但原料（可用的小分子）有限，複製者之間便進入競爭。此時三種特性決定勝負：複製的「壽命 (longevity)」夠長、「繁殖速度 (fecundity)」夠快、「複製精準度 (copying-fidelity)」夠高的變體，會在濃湯中愈來愈多。偶爾的複製錯誤帶來變異，而變異加上這場天擇篩選，就是演化的引擎——重點是，這一切早在任何生命體、任何身體出現之前，就已在分子層次運轉。</p><div class="section-break">◆ ◆ ◆</div><p><strong>關鍵實例：</strong>想像濃湯裡兩種複製者。一種拷貝速度快但容易散架、也常抄錯；另一種拷貝較慢卻結構穩固、抄得又準。長期下來，穩固而精準的那一型會累積出更多能延續的後代拷貝，逐漸主宰整鍋湯。勝出的從來不是「最複雜」或「最高等」的，而是最擅長讓自己的拷貝存續下去的那一型。</p><p><strong>啟示：</strong>最關鍵的一步是：隨著競爭加劇，複製者開始「打造工具」來保護自己、搶奪原料——最初可能只是一層蛋白質外殼。這些用來保存與傳遞複製者的容器，就是「生存機器」的雛形。換句話說，是複製者先存在，身體才被造出來為它服務，而不是反過來。</p><p class="thought-question">🤔 思考：如果生命真正的主角是那個「想被複製」的分子，那麼我們看重的複雜、智慧與美麗，會不會只是複製者為了活下去而順手打造出來的副產品？</p>`,
      en: `<p><strong>Core claim:</strong> This chapter traces life back to its origin. Dawkins pictures the ancient Earth's "primeval soup," where by chance the first molecule able to copy itself appeared. He calls it a replicator. The story of life is, at bottom, a history of competition among replicators to get themselves copied more.</p><p><strong>The argument:</strong> Once a self-copying molecule exists, exponential multiplication begins, but the raw materials (available small molecules) are limited, so replicators start to compete. Three properties then decide the winners: variants with enough longevity, high enough fecundity, and high enough copying-fidelity come to dominate the soup. Occasional copying errors supply variation, and variation plus this selective sieve is the engine of evolution. Crucially, all of this ran at the molecular level long before any organism, any body, existed.</p><div class="section-break">◆ ◆ ◆</div><p><strong>Key example:</strong> Imagine two replicators in the soup. One copies fast but falls apart easily and blunders often; the other copies more slowly yet holds together and copies accurately. Over time the sturdy, accurate type accumulates more enduring descendant copies and gradually rules the pot. What wins is never the "most complex" or "highest" form, but the type best at keeping its own copies in circulation.</p><p><strong>Takeaway:</strong> Here is the decisive step. As competition sharpens, replicators begin to "build tools" to protect themselves and grab resources, perhaps at first only a protective protein coat. Those containers for preserving and propagating replicators are the seeds of the survival machine. In other words, the replicator came first, and the body was built to serve it, not the other way around.</p><p class="thought-question">🤔 Reflect: If life's true protagonist is a molecule that "wants" to be copied, might the complexity, intelligence, and beauty we prize be mere by-products the replicator threw together simply in order to survive?</p>`
    }
  },
  3: {
    num: { zh: '第 3 章', en: 'Chapter 3' },
    title: { zh: '不朽的雙螺旋', en: 'Immortal Coils' },
    epigraph: {
      zh: '「身體會凋零，基因卻能拷貝著自己，活過無數世代。」',
      en: '“Bodies wear out, but a gene can copy itself across countless generations.”'
    },
    body: {
      zh: `<p><strong>核心論點：</strong>本章解釋：為什麼真正該被視為天擇單位 (unit of selection) 的，是基因，而不是個體或身體。答案在於「持續性」——基因近乎「不朽」，可以透過一份份拷貝延續無數世代；而個體與身體則短暫、獨一無二、注定消逝。</p><p><strong>論證：</strong>道金斯把基因定義為一段夠短、能在世代間穩定傳遞的 DNA。它的特別之處在於：你的身體是父母基因洗牌後、只出現這一次的獨特組合，會隨你死去而永遠消失；但構成你的每一段基因，卻能以完全相同的資訊拷貝形式，跳進你的子女、孫輩，一路傳下去。天擇要能「累積」出精密的適應，就需要一個能跨世代穩定存續、供比較與篩選的單位——身體太易逝，只有基因這種近乎永生的複製者能勝任這個角色。</p><div class="section-break">◆ ◆ ◆</div><p><strong>關鍵實例：</strong>好比一段代代相傳的抄本文字。裝訂的那本書會破損、丟失（那是身體），但只要文字被一字不差地抄進新的一本本裡，這段「內容」本身就能存活數百年、遠超任何一本實體書的壽命。基因就是那段「內容」：載體來來去去，資訊本身卻能延續。</p><p><strong>啟示：</strong>從基因視角看，個體不過是基因暫時的居所與運輸工具。天擇篩選的其實是不同基因在基因庫中此消彼長的相對成敗——哪些基因的拷貝更善於世世代代地存續下去。理解了這點，就能明白為什麼「基因的利益」才是解釋行為最穩固的立足點。</p><p class="thought-question">🤔 思考：如果構成你的基因早在你出生前就已存在、也將在你死後繼續被拷貝下去，那麼「你」這個獨一無二的個體，究竟是主角，還是基因漫長旅程中一段轉瞬即逝的載具？</p>`,
      en: `<p><strong>Core claim:</strong> This chapter explains why the true unit of selection is the gene, not the individual or the body. The answer is persistence. A gene is nearly immortal: it can endure across countless generations through copy after copy, whereas an individual and its body are fleeting, unique, and doomed to pass away.</p><p><strong>The argument:</strong> Dawkins defines a gene as a stretch of DNA short enough to be passed down stably between generations. What makes it special is this: your body is a one-time-only shuffle of your parents' genes, a unique combination that vanishes forever when you die. Yet each gene that makes you up can leap, as an identical copy of information, into your children, your grandchildren, and onward. For selection to accumulate intricate adaptations, it needs a unit that persists stably across generations to be compared and sieved. Bodies are too perishable; only a near-immortal replicator like the gene can play that role.</p><div class="section-break">◆ ◆ ◆</div><p><strong>Key example:</strong> Think of a text copied by hand down the generations. The bound volume it sits in tears and gets lost (that is the body), but as long as the words are copied faithfully into fresh volumes, the "content" itself can survive for centuries, far outlasting any single physical book. The gene is that content: carriers come and go, yet the information endures.</p><p><strong>Takeaway:</strong> From the gene's-eye view, the individual is merely a gene's temporary dwelling and vehicle. What selection really sifts is the shifting relative success of different genes in the gene pool, which copies prove better at persisting generation after generation. Grasp this, and you see why "the gene's interest" is the most solid footing for explaining behavior.</p><p class="thought-question">🤔 Reflect: If the genes that compose you existed before you were born and will go on being copied after you die, is "you," the unique individual, the protagonist, or just a fleeting vehicle in the gene's very long journey?</p>`
    }
  },
  4: {
    num: { zh: '第 4 章', en: 'Chapter 4' },
    title: { zh: '基因機器', en: 'The Gene Machine' },
    epigraph: {
      zh: '「基因無法即時操控，於是它造了一個會自己判斷的大腦。」',
      en: '“Unable to steer in real time, genes built a brain that decides for itself.”'
    },
    body: {
      zh: `<p><strong>核心論點：</strong>本章描繪身體如何成為基因的機器人。基因是每個「生存機器」的建造者與程式設計者，但它面對一個根本限制：它無法即時遙控身體的每一個當下反應。解法是打造大腦——一台能自己感知、預測、決策的控制器。</p><p><strong>論證：</strong>問題出在時間差。基因的作用是化學性、緩慢的，而生存所需的反應往往必須在瞬息之間完成：獵食者撲來、食物閃現、地面塌陷。基因不可能坐在遠端逐一下指令。於是天擇偏好那些「懂得預先寫好通用策略」的基因：它們不規定每個動作，而是在大腦裡裝進「經驗法則 (rule of thumb)」，以及用內建的模型去模擬、預測情境的能力。基因負責設定大方向的目標（例如「趨近甜味、避開痛覺」），至於當下該怎麼做，就交給這台會臨場應變的機器自行決定。</p><div class="section-break">◆ ◆ ◆</div><p><strong>關鍵實例：</strong>就像一位無法親臨太空、只能在發射前寫好程式的工程師，面對通訊有數分鐘延遲的火星探測器。他不可能即時搖桿操控，只能事先賦予探測器規則與自主判斷力，讓它落地後自己應付未知地形。基因對大腦，正是這種「事前程式設計、事後放手」的關係——這也正是意識與自主決策得以浮現的縫隙。</p><p><strong>啟示：</strong>正因為基因只能間接、延遲地施加影響，機器（也就是我們）便獲得了相當程度的自主與彈性，甚至能做出違背基因原始「利益」的選擇。這道時間差，既是基因把主導權外包出去的無奈，也是我們之所以能不完全被基因決定的空間。</p><p class="thought-question">🤔 思考：如果你的大腦是基因為了應付牠們鞭長莫及的世界而放手打造的自主機器，那麼今天你做的每一個看似自由的決定，是在執行牠們寫好的規則，還是真的走出了程式之外？</p>`,
      en: `<p><strong>Core claim:</strong> This chapter portrays the body as the gene's robot. Genes are the builders and programmers of every survival machine, but they face a fundamental limit: they cannot remote-control the body's every moment-to-moment response. The solution is to build a brain, a controller that can sense, predict, and decide on its own.</p><p><strong>The argument:</strong> The problem is a time lag. Gene action is chemical and slow, yet the responses survival demands must often happen in an instant: a predator lunges, food flickers past, the ground gives way. Genes cannot sit at a distance issuing each command. So selection favors genes that "write general strategies in advance": rather than dictating every move, they install rules of thumb in the brain, plus the capacity to run internal models that simulate and predict situations. The genes set the broad goals (say, "approach sweetness, avoid pain"), and how to act in the moment is left to this machine that improvises on the spot.</p><div class="section-break">◆ ◆ ◆</div><p><strong>Key example:</strong> It is like an engineer who cannot travel to space and can only write the program before launch, facing a Mars rover whose signals arrive minutes late. Real-time joystick control is impossible; all the engineer can do is equip the rover with rules and autonomous judgment beforehand, so that once it lands it copes with unknown terrain by itself. The gene-brain relationship is exactly this "program in advance, then let go," and it is the very gap through which consciousness and autonomous decision can emerge.</p><p><strong>Takeaway:</strong> Precisely because genes can influence us only indirectly and after a delay, the machine (that is, we) gains real autonomy and flexibility, even the ability to make choices that run against the genes' original "interests." This time lag is at once the genes' reluctant outsourcing of control and the very room that lets us not be wholly determined by them.</p><p class="thought-question">🤔 Reflect: If your brain is an autonomous machine the genes built and released to cope with a world beyond their reach, is every seemingly free decision you make today just running the rules they wrote, or have you genuinely stepped outside the program?</p>`
    }
  }
});
Object.assign(CHAPTER_CONTENT, {
  5: {
    num: { zh: '第 5 章', en: 'Chapter 5' },
    title: { zh: '攻擊行為：穩定與自私的機器', en: 'Aggression: Stability and the Selfish Machine' },
    epigraph: {
      zh: '「動物不會為了物種好而克制廝殺，牠們克制，只因為克制對自己的基因更划算。」',
      en: '“Animals do not hold back from all-out war for the good of the species; they hold back because restraint pays their own genes better.”'
    },
    body: {
      zh: `<p><strong>核心論點：</strong>同種動物之間的爭鬥，遠比我們想像的節制——很少真的往死裡打。但這種克制並非出於高尚，也不是「為了物種存續」，而是因為在演化的算計裡，一味逞凶對自己的基因並不划算。真正勝出的行為模式，是那些一旦普及就無法被少數變異者佔便宜的策略。</p><p><strong>論證：</strong>梅納德·史密斯把賽局理論引入演化，提出「演化穩定策略」（ESS）：若某個策略組合一旦在族群中普及，任何採取不同打法的變異個體都無法獲得更高報酬，這個組合就會穩定下來。關鍵字是「穩定」，不是「對大家最好」。經典的鷹鴿賽局裡，「鷹」逢戰必拚、「鴿」只虛張聲勢見血就退。純鷹族群會被和平的鴿入侵，純鴿族群又會被兇狠的鷹入侵——最後停在一個鷹鴿共存的比例，誰都無法靠改變打法佔到便宜。這個平衡點不必然讓族群整體活得最好，它只是「進不去、也退不出」而已。</p><div class="section-break">◆ ◆ ◆</div><p><strong>關鍵實例：</strong>許多動物的爭鬥像儀式——鹿比吼聲、比體型，真正流血的衝突意外地少。還有「資深者優先」這類看似武斷的慣例：先佔地盤者往往被默認為勝方，挑戰者多半知難而退。這不是紳士協定，而是一種穩定約定：只要大家都遵守「持有者贏」，破壞規則去死拚的個體反而更容易受傷、更不划算。約定本身無關對錯，只要它穩定就會延續。</p><p><strong>啟示：</strong>自然界的和平，往往不是善意的產物，而是自私算計相互制衡後的均衡。用「對物種有利」來解釋動物行為常常是錯的方向；真正該問的是「這個策略能不能抵抗變異者入侵」。穩定，才是演化篩選的準繩。</p><p class="thought-question">🤔 思考：如果一種「更愛好和平」的打法能被更兇狠的變異者輕易佔便宜，那它再美好也留不下來——你能想到人類社會裡哪些看似不公的慣例，其實只是因為「夠穩定」才存活至今？</p>`,
      en: `<p><strong>Core claim:</strong> Fights between members of the same species are far more restrained than we assume; animals rarely fight to the death. But that restraint is not noble, and it is not for the good of the species. It survives because unrestrained aggression usually does not pay a creature's own genes. The behaviour patterns that win are the ones that, once common, cannot be exploited by a rare mutant playing differently.</p><p><strong>The argument:</strong> Maynard Smith brought game theory into evolution with the idea of an evolutionarily stable strategy (ESS): a strategy mix that, once widespread in a population, cannot be beaten by any individual adopting a different tactic. The operative word is stable, not best-for-everyone. In the classic hawk-dove game, a hawk always escalates while a dove bluffs and retreats at the first sign of blood. An all-dove population is invaded by hawks; an all-hawk population is invaded by doves; the system settles at a mix where no one can gain by switching. That balance need not be the arrangement that keeps the population healthiest; it is simply the point no mutant can breach.</p><div class="section-break">◆ ◆ ◆</div><p><strong>Key example:</strong> Many contests are ritualised, deer roar and size each other up, and actual bloodshed is surprisingly rare. There are also arbitrary-looking conventions such as respect for prior ownership: whoever holds the territory tends to be treated as the winner, and challengers back down. This is no gentlemen's agreement, it is a stable convention. So long as everyone plays holder-wins, the individual who breaks the rule and fights to the death is likelier to get hurt and comes off worse. The convention need not be fair; it only needs to be stable to persist.</p><p><strong>Takeaway:</strong> Peace in nature is usually not the product of goodwill but the equilibrium of competing selfish calculations. Explaining animal behaviour by what is good for the species is often the wrong question. The right one is whether a strategy can resist invasion by a mutant. Stability, not virtue, is what selection preserves.</p><p class="thought-question">🤔 Reflect: If a more peace-loving tactic can be easily exploited by a nastier mutant, it will not last no matter how appealing it is. Which seemingly unfair conventions in human society persist mainly because they are stable?</p>`
    }
  },
  6: {
    num: { zh: '第 6 章', en: 'Chapter 6' },
    title: { zh: '基因的算計', en: 'Genesmanship' },
    epigraph: {
      zh: '「基因並不只藏在你身上——你的兄弟姊妹、子女、表親，都各自帶著它的拷貝。」',
      en: '“A gene does not sit only in you: copies of it ride inside your siblings, your children, your cousins.”'
    },
    body: {
      zh: `<p><strong>核心論點：</strong>如果基因是自私的，動物為什麼會冒險去幫助親屬？答案是：親屬體內帶著同一個基因的拷貝。一個「使個體照顧血親」的基因，其實是在照顧藏在別具身體裡的自己。這就是親屬選擇（kin selection）——利他行為可以從純粹自私的基因中演化出來。</p><p><strong>論證：</strong>漢彌爾頓提出的思路是：衡量一個利他行為值不值得，要看「親緣係數 r」——你與對方共享某基因拷貝的機率。父母子女之間、親兄弟姊妹之間 r 約為 1/2，祖孫與同父異母手足約 1/4，表親約 1/8。基因會「傾向」促成利他，只要利益乘上親緣係數大於代價（利益 × r 大於代價）。這就是漢彌爾頓法則。由此延伸出「內含適應度」的概念：衡量一個個體的演化成功，不能只算牠自己生了幾個後代，還要把牠對親屬繁殖的影響、按親緣係數折算後一併計入。所謂「自私的基因」，在血緣網絡裡表現出來的，正是對親屬的利他。</p><div class="section-break">◆ ◆ ◆</div><p><strong>關鍵實例：</strong>經常被引用的是那句半開玩笑的話：願意為兩個兄弟或八個表親而死，這在基因帳本上剛好打平。真實世界裡，警戒叫聲是好例子——發出警報的個體讓自己更顯眼、更危險，卻讓附近的親屬得以逃生。若受惠的多是帶著相同基因的血親，這種看似犧牲的行為在基因層次上反而是划算的投資。動物對「誰是近親」的判斷未必精確，往往靠「就近、熟悉、同巢」等粗略線索代勞。</p><p><strong>啟示：</strong>血緣利他不需要動物會算數，也不需要牠們懂得什麼是基因。天擇只是讓那些「碰巧幫到親屬」的基因留存下來，而效果看起來就像精打細算。親情之所以普遍，不是因為它超越自私，而恰恰是自私基因在多具身體間的延伸。</p><p class="thought-question">🤔 思考：如果連「無私的親情」骨子裡都是基因為自己的拷貝算計，那麼「真正的無私」還有沒有立足之地——還是它只是我們替這套算計取的美名？</p>`,
      en: `<p><strong>Core claim:</strong> If genes are selfish, why do animals risk themselves to help relatives? Because relatives carry copies of the same genes. A gene that makes its bearer care for kin is, in effect, looking after copies of itself lodged in other bodies. This is kin selection, and it shows how altruism can evolve straight out of purely selfish genes.</p><p><strong>The argument:</strong> Hamilton's insight was to judge an act of altruism by the coefficient of relatedness, r, the probability that a given gene copy is shared with the recipient. Between parent and child, or full siblings, r is about one half; grandparent and grandchild, or half-siblings, about a quarter; first cousins about an eighth. A gene will tend to favour altruism whenever the benefit multiplied by r exceeds the cost, which is Hamilton's rule. From this comes inclusive fitness: an individual's evolutionary success is measured not only by its own offspring but by its effect on the reproduction of relatives, each discounted by relatedness. In a web of kin, the selfish gene expresses itself as altruism toward blood relations.</p><div class="section-break">◆ ◆ ◆</div><p><strong>Key example:</strong> There is the half-joking line that one might lay down one's life for two brothers or eight cousins, since that roughly breaks even in the genetic ledger. In the real world, alarm calls are a clean illustration: the caller makes itself more conspicuous and more endangered while letting nearby relatives escape. If those who benefit are mostly kin carrying the same gene, this apparent sacrifice is actually a paying investment at the level of the gene. Animals need not judge kinship precisely; they lean on rough cues such as proximity, familiarity, and sharing a nest.</p><p><strong>Takeaway:</strong> Kin altruism requires no arithmetic and no understanding of genes. Selection simply preserves genes that happen to help relatives, and the result merely looks calculated. Family devotion is common not because it rises above selfishness but precisely because it is the selfish gene reaching across several bodies.</p><p class="thought-question">🤔 Reflect: If even self-sacrificing family love is, at bottom, genes looking after their own copies, is there any room left for genuine selflessness, or is that just the flattering name we give the same calculation?</p>`
    }
  },
  7: {
    num: { zh: '第 7 章', en: 'Chapter 7' },
    title: { zh: '家庭計畫', en: 'Family Planning' },
    epigraph: {
      zh: '「動物節制生育，不是為了族群不至於太擠，而是為了讓自己傳下最多能活下來的後代。」',
      en: '“When animals limit their brood, it is not to spare the population from crowding but to leave as many surviving offspring as they can.”'
    },
    body: {
      zh: `<p><strong>核心論點：</strong>許多動物並不會拚命多生，而是把後代數量控制在某個「剛好」的水準。過去有人以為這是為了避免族群過度膨脹、消耗資源——一種為群體犧牲的利他。但更站得住腳的解釋是：節制生育本身就是自私基因的最適策略，因為生太多反而讓能活到成年的後代變少。</p><p><strong>論證：</strong>這裡要區分兩種「限制人口」的說法。一種是溫-愛德華茲式的群體選擇論：個體為了避免整群餓死而自願少生。達爾文主義的邏輯很難支持這種說法——因為只要出現一個「照樣多生」的自私變異者，牠的後代很快就會淹沒那些克制者，利他基因無法存續。另一種是拉克的解釋：親代所能投入的資源有限，養育每個後代都有成本；生得太多，每個都分不到足夠照料，存活率下降，最後長成的反而更少。存在一個能讓「成功養大的後代數」最大化的最適窩卵數。這不是為族群著想，而是個體為自己的基因盤算——「生」與「養」之間必須取捨。</p><div class="section-break">◆ ◆ ◆</div><p><strong>關鍵實例：</strong>鳥類的窩卵數是經典案例。拉克發現，鳥往往下的蛋數並非牠生理上能下的最大值，而是接近「能成功養活的雛鳥數」的最適值。人為在巢中多加幾顆蛋，親鳥未必能把全部雛鳥都餵飽，結果整窩活下來的反而不比原本多、甚至更少。動物也會依據環境好壞、食物多寡「調整」生育投入——豐年多生、荒年少生，都是為了讓自己最終傳下最多存活後代。</p><p><strong>啟示：</strong>看似「懂得節制、顧全大局」的生育行為，其實是精算過的自私。演化不會偏好那些「為了大家而少生」的個體，只會偏好那些「生得剛好、養得起、傳得下去」的個體。慷慨的表象底下，仍是基因對自身拷貝數的極大化。</p><p class="thought-question">🤔 思考：既然「少生」可以是純粹自利的最適解，那我們該如何分辨一個克制的行為，究竟是真的顧全群體，還是只是把自私算得更精？</p>`,
      en: `<p><strong>Core claim:</strong> Many animals do not breed flat out; they hold their brood to a level that is just right. It was once thought this served to keep populations from overrunning their resources, a sacrifice for the group. The sturdier explanation is that limiting reproduction is itself the selfish gene's best strategy, because breeding too much leaves fewer offspring alive to adulthood.</p><p><strong>The argument:</strong> Two accounts of population restraint must be told apart. One is Wynne-Edwards-style group selection: individuals breed less to keep the whole group from starving. Darwinian logic struggles to support this, because a single selfish mutant that keeps on breeding would soon swamp the restrained ones, so the altruistic gene cannot persist. The other is Lack's explanation: a parent's resources are finite, and rearing each offspring costs; produce too many and none gets enough care, survival drops, and fewer make it to maturity. There is an optimal clutch size that maximises the number successfully reared. This is not concern for the group but an individual reckoning for its own genes, a trade-off between bearing and rearing.</p><div class="section-break">◆ ◆ ◆</div><p><strong>Key example:</strong> Clutch size in birds is the classic case. Lack found that birds often lay not the largest number they physically could but a number close to what they can successfully rear. Add extra eggs to a nest and the parents may fail to feed every chick, so the whole brood that survives is no larger, and can be smaller, than before. Animals also adjust their breeding effort to conditions, more in good years and fewer in lean ones, all to leave the greatest number of surviving young.</p><p><strong>Takeaway:</strong> Breeding that looks like prudent restraint for the common good is in fact carefully calculated selfishness. Evolution does not favour individuals who breed less for everyone's sake, only those who breed the right amount, can afford to rear it, and pass it on. Beneath the generous appearance, genes are still maximising the number of their own copies.</p><p class="thought-question">🤔 Reflect: If breeding less can be a purely self-serving optimum, how do we ever tell whether an act of restraint truly serves the group, or is just selfishness calculated more finely?</p>`
    }
  },
  8: {
    num: { zh: '第 8 章', en: 'Chapter 8' },
    title: { zh: '世代之戰', en: 'Battle of the Generations' },
    epigraph: {
      zh: '「親代與子代基因上並不完全一致，於是連母親的懷抱裡，也藏著一場靜靜的拉鋸。」',
      en: "“Parent and child are not genetically identical, so even a mother's embrace conceals a quiet tug-of-war.”"
    },
    body: {
      zh: `<p><strong>核心論點：</strong>親代與子代的利益並非完全一致。父母要在所有子女之間公平分配有限的投資，好讓自己傳下的後代總數最大；但每個子女從自己的角度出發，都想要拿到比「父母的最適分配」更多的那一份。這種內建的利益落差，就是崔弗斯所說的「親子衝突」（parent-offspring conflict）。</p><p><strong>論證：</strong>從基因看，一個孩子與自己的關係（r=1）比與手足的關係（r=1/2）更近。因此父母眼中「對整體後代最划算」的分配，在孩子眼中往往給自己太少。父母傾向平均照顧、適時把資源轉向下一胎；孩子則傾向多爭一點、多吵一點、晚一點被斷奶。這就是親代投資（parental investment）成為稀缺資源後必然出現的拉鋸。子代並非被動接受分配，牠們演化出各種手段去「爭取」超額投資——而父母也演化出反制，以免被單一子女掏空、犧牲了其他後代。這是一場沒有絕對贏家的軍備競賽。</p><div class="section-break">◆ ◆ ◆</div><p><strong>關鍵實例：</strong>斷奶衝突是最鮮明的例子。母獸想在某個時點停止哺乳、把精力投向下一胎，因為繼續餵這隻的邊際效益已經下降；但小獸仍想繼續吃奶，於是又是哀鳴又是糾纏。雛鳥的討食也是如此：牠們用誇張的張嘴與叫聲競相索取，彷彿在對父母「喊價」。手足之間更是直接競爭同一份口糧，有些物種甚至出現手足相殘。這些都不是家庭失和的意外，而是基因利益不完全重疊的必然結果。</p><p><strong>啟示：</strong>「天下父母心」與「孝順子女」的溫情圖像，其實建立在一個不對稱的基因帳本上。家庭既是合作的場域，也是持續協商與角力的場域。理解這一點，不是要否定親情的真實，而是看清它為何常伴隨著我們熟悉的哭鬧、任性與拉扯。</p><p class="thought-question">🤔 思考：如果孩子「討得比該得的多」是基因寫進去的本能，那麼父母的「一碗水端平」與孩子的「多要一點」之間，究竟有沒有一個真正公平的分配點——還是公平本身就是雙方永遠談不攏的東西？</p>`,
      en: `<p><strong>Core claim:</strong> The interests of parent and offspring are not identical. A parent must divide limited investment fairly among all its young so as to maximise its total surviving descendants; but each offspring, from its own vantage, wants more than the parent's optimal share. This built-in gap of interest is what Trivers called parent-offspring conflict.</p><p><strong>The argument:</strong> Genetically, a child is more closely related to itself (r = 1) than to a sibling (r = one half). So the division that looks best to the parent across all its young often looks too meagre to the individual child. Parents tend toward even-handed care and toward shifting resources to the next brood at the right time; children tend to grab a little more, beg a little louder, and resist weaning a little longer. This is the tug-of-war that must arise once parental investment becomes a scarce resource. Offspring are not passive recipients; they evolve tactics to extract extra investment, and parents in turn evolve counter-measures so that no single child drains them at the expense of the rest. It is an arms race with no outright winner.</p><div class="section-break">◆ ◆ ◆</div><p><strong>Key example:</strong> Weaning conflict is the sharpest case. A mother wants to stop nursing at the point where the marginal payoff of feeding this offspring has fallen, so she can invest in the next; the youngster still wants milk, and so it whines and pesters. Nestlings begging for food do the same, gaping and calling in an escalating scramble that amounts to bidding against one another for the parent's attention. Siblings compete directly for the same rations, and in some species sibling killing occurs. None of this is an accident of family discord; it follows inevitably from the incomplete overlap of genetic interests.</p><p><strong>Takeaway:</strong> The warm picture of devoted parents and dutiful children rests on an asymmetric genetic ledger. The family is both an arena of cooperation and a site of continual negotiation and struggle. Grasping this does not deny that family love is real; it shows why it so often comes with the familiar crying, wilfulness, and pulling that we know so well.</p><p class="thought-question">🤔 Reflect: If a child's tendency to demand more than its fair share is written in by its genes, is there really any point of division that is truly fair between a parent's even hand and a child's wanting more, or is fairness itself something the two sides can never settle?</p>`
    }
  }
});
Object.assign(CHAPTER_CONTENT, {
  9: {
    num: { zh: '第 9 章', en: 'Chapter 9' },
    title: { zh: '兩性之戰', en: 'Battle of the Sexes' },
    epigraph: {
      zh: '「當雙方都想合作卻各懷算計，最公平的分工也會滲進一絲互不信任。」',
      en: '“Even a partnership that both sides want can be laced with mutual suspicion.”'
    },
    body: {
      zh: '<p><strong>核心論點：</strong>兩性之間之所以存在利益衝突，根源不在性別本身，而在一項不對稱：定義「雄」與「雌」的，正是性細胞的大小差異。雌方提供又大又稀少、備滿養分的卵；雄方提供又小又量多、幾乎不帶資源的精子。從受孕那一刻起，母方已投下較多本錢，這種親代投資（parental investment）的失衡，讓雙方對「誰該繼續付出、誰該趁機開溜」抱著相反的盤算。</p><p><strong>論證：</strong>一旦母方先押下較大賭注，她在演化上就更「捨不得」放棄這個孩子——因為重來一次成本高昂；而父方投入既少，拋下這一胎另尋新對象的損失就小得多。於是雙方各自演化出對抗策略。母方傾向精挑對象、要求對方先付出誠意（如築巢、餵食、長期陪伴）以篩掉只想留種就走的雄性；雄方則在「顧家」與「花心」兩條路線間權衡。這也解釋了性擇（sexual selection）：當雌性偏好某種雄性特徵，該特徵便會被一代代放大，哪怕它對生存毫無用處、甚至是累贅。</p><div class="section-break">◆ ◆ ◆</div><p><strong>關鍵實例：</strong>作者以賽局的方式想像雌性的兩種策略——「羞怯型」堅持長期追求期才肯交配，「輕率型」則來者不拒；雄性也分「忠貞型」與「濫情型」。哪種組合能穩定共存，取決於背叛與被拋棄的代價高低。孔雀華麗到礙事的尾羽，就是性擇失控的招牌：它不利逃命，卻因雌孔雀世代偏愛而被推到極致，成了「我扛得起這累贅，可見我夠強」的活廣告。</p><p><strong>啟示：</strong>家庭並非全然溫情的避風港，而是一場利益既重疊又衝突的長期談判。所謂「忠貞」「挑剔」「炫耀」等行為，未必出於情感或道德，而可能是基因為了在不對稱賭局中不吃虧，替載體寫好的談判腳本。理解這點，不是要人變得冷酷，而是看清衝動背後的邏輯。</p><p class="thought-question">🤔 思考：如果雌雄雙方的初始投資一樣大，我們熟悉的求偶、忠誠與炫耀行為會不會整個翻轉？</p>',
      en: '<p><strong>Core claim:</strong> Conflict between the sexes springs not from gender as such but from one asymmetry: what defines male versus female is the size difference between their sex cells. The female contributes a large, scarce, nutrient-loaded egg; the male contributes tiny, abundant, resource-poor sperm. From conception onward the mother has already staked more, and this imbalance in parental investment sets the two parties scheming in opposite directions about who keeps paying and who slips away.</p><p><strong>The argument:</strong> Because the mother commits the bigger stake first, evolution makes her more reluctant to abandon the offspring, since starting over is costly. The father, having invested little, loses far less by deserting this brood and seeking a fresh mate. So each sex evolves counter-strategies. Females tend to be choosy, demanding proof of commitment (nest-building, feeding, sticking around) to screen out males who only want to fertilize and leave. Males weigh a stay-at-home line against a philandering one. This also explains sexual selection: once females favor a particular male trait, that trait gets amplified generation after generation, even if it is useless or a handicap for survival.</p><div class="section-break">◆ ◆ ◆</div><p><strong>Key example:</strong> The author models female strategies as a game -- a coy type that insists on a long courtship before mating, and a fast type that does not; males split into faithful and philanderer types. Which mix stays stable depends on how costly desertion and betrayal are. The peacock tail, gorgeous to the point of hazard, is the poster child of runaway sexual selection: it hurts escape yet was pushed to extremes by generations of peahen preference, advertising in effect I can carry this burden and still thrive, so I must be fit.</p><p><strong>Takeaway:</strong> A family is less a haven of pure warmth than a long negotiation of overlapping but clashing interests. Fidelity, choosiness, showing off -- these need not spring from emotion or morality; they may be negotiating scripts the genes wrote to avoid losing an asymmetric gamble. Seeing this is not a call to be cold, but a way to read the logic behind the impulse.</p><p class="thought-question">🤔 Reflect: If both sexes started with equally large investments, would the courtship, loyalty, and display we take for granted flip entirely?</p>'
    }
  },
  10: {
    num: { zh: '第 10 章', en: 'Chapter 10' },
    title: { zh: '你幫我抓背，我搭你便車', en: "You Scratch My Back, I'll Ride on Yours" },
    epigraph: {
      zh: '「合作能演化出來，靠的不是善意，而是重逢的可能。」',
      en: '“Cooperation evolves not from goodwill but from the prospect of meeting again.”'
    },
    body: {
      zh: '<p><strong>核心論點：</strong>利他行為未必要限縮在血緣之間。即使是毫無親屬關係的個體，只要能長期相處、彼此記得對方過去的表現，「你今天幫我、我改天回報你」這種互惠利他（reciprocal altruism）也能在演化中站穩腳跟。條件很嚴：得能認出彼此、記得誰守信誰背叛，並且對背叛者收回幫助。</p><p><strong>論證：</strong>單次相遇時，佔便宜（接受幫助卻不回報）永遠划算，合作因此難以起步。但若同一群個體會反覆碰面，情況就變了：一個「先釋出善意、但被騙過一次後就不再幫該對象」的策略，能同時避開被無限剝削，又留住與其他守信者互惠的長期紅利。麻煩在於「騙子」——它享受別人幫忙卻從不回報，短期內比老實的合作者更佔便宜。唯一能壓制騙子的防線，是記憶與辨識：把每一次互動的對象記在心裡，對曾經背叛的個體斷絕合作，讓佔便宜變得不再划算。</p><div class="section-break">◆ ◆ ◆</div><p><strong>關鍵實例：</strong>清潔魚游進大魚口中啄食寄生蟲，大魚明明可以一口吞下這頓送上門的午餐，卻多半忍住——因為固定的清潔站與可辨識的老主顧，讓「今天不吃牠、明天還有得清」成了更划算的選擇。吸血蝙蝠則會把當晚多吸到的血反芻分給挨餓的同伴；牠們住在穩定的群落、彼此相熟，今晚我救你、改天你救我，這份保險讓不確定的覓食風險被攤平。</p><p><strong>啟示：</strong>穩定的合作社會，底層不必是無私的愛，而是三個冷硬的前提：夠長的相處、能認人、會記帳。人類尤其擅長這套——我們的記憶、語言與名聲機制，讓互惠得以擴展到龐大的陌生人網絡。理解這點，能讓我們更看重「重複往來」與「聲譽」為何是信任的真正地基。</p><p class="thought-question">🤔 思考：如果人們再也認不出彼此、也記不住誰曾背叛，我們今天視為理所當然的哪些信任會最先崩解？</p>',
      en: '<p><strong>Core claim:</strong> Altruism need not be confined to kin. Even among unrelated individuals, a you-help-me-and-I-repay-you arrangement -- reciprocal altruism -- can gain a firm evolutionary foothold, provided they associate over the long run and remember one another past conduct. The conditions are strict: they must recognize each other, recall who kept faith and who cheated, and withdraw help from cheats.</p><p><strong>The argument:</strong> In a one-off encounter, taking help without repaying always pays, so cooperation struggles to start. But when the same individuals meet again and again, the calculus shifts: a strategy that offers goodwill first yet stops helping anyone who has cheated it once both avoids endless exploitation and keeps the long-term dividend of trading favors with reliable partners. The trouble is the cheat -- one who accepts help but never returns it and out-earns honest cooperators in the short term. The only defense that suppresses cheats is memory and recognition: keep track of who you dealt with, cut off cooperation with proven betrayers, and make cheating stop paying.</p><div class="section-break">◆ ◆ ◆</div><p><strong>Key example:</strong> Cleaner fish swim into a big fish mouth to pick off parasites; the big fish could easily swallow this free lunch, yet usually holds back -- because fixed cleaning stations and recognizable regular customers make sparing the cleaner today (to be cleaned again tomorrow) the better deal. Vampire bats regurgitate a share of a good night blood haul to a starving roost-mate; living in stable, familiar colonies, they run an I-save-you-tonight, you-save-me-later insurance that smooths out the risk of an unlucky hunt.</p><p><strong>Takeaway:</strong> A stable cooperative society need not rest on selfless love, but on three hard conditions: long enough association, the ability to recognize individuals, and the habit of keeping accounts. Humans are unusually good at this -- our memory, language, and reputation machinery let reciprocity scale to vast networks of strangers. Seeing this clarifies why repeated dealings and reputation are the real foundations of trust.</p><p class="thought-question">🤔 Reflect: If people could no longer recognize each other or remember who had betrayed them, which of the trusts we take for granted would collapse first?</p>'
    }
  },
  11: {
    num: { zh: '第 11 章', en: 'Chapter 11' },
    title: { zh: '迷因：新的複製者', en: 'Memes: The New Replicators' },
    epigraph: {
      zh: '「當一個念頭從一顆腦袋跳進另一顆腦袋，它就已經在為自己而活。」',
      en: '“The moment an idea leaps from one brain to another, it has begun living for itself.”'
    },
    body: {
      zh: '<p><strong>核心論點：</strong>基因不是宇宙間唯一的複製者（replicator）。在人類文化裡，出現了一種新的複製者——迷因（meme）：一段曲調、一個觀念、一句口號、一種時尚或信仰。它像基因一樣，會從一顆大腦「複製」到另一顆大腦，靠模仿與傳播來擴散、競爭、演化。</p><p><strong>論證：</strong>作者主張，演化的真正主角是任何能自我複製的東西，而非特定的化學分子。基因湯之外，人腦與文化構成了一鍋新的「迷因湯」。迷因的成敗同樣取決於三種特質：複製的忠實度、存活的壽命、以及散播的速度。一個朗朗上口、易記易傳的想法，會在人腦間快速繁衍，未必因為它對宿主有益——就像有些基因對載體未必有利。迷因彼此也在爭奪有限的資源：人的注意力、記憶容量與傳播時間。</p><div class="section-break">◆ ◆ ◆</div><p><strong>關鍵實例：</strong>作者以「上帝」這個觀念為例：它之所以能跨越千百年、遍布各文化，未必是因為被證明為真，而是因為它作為迷因極具「存活價值」——它回應了人對意義與慰藉的深層渴求，又常與一整套彼此加固的迷因（如信仰、來世、儀式）綑綁成群，互相扶持、更難被質疑撼動，於是一代代穩定地複製下去。</p><p><strong>啟示：</strong>我們既是基因的載體，也是迷因的載體，時常被這兩類自私複製者的利益推著走。但全書結尾留下一線希望：人類擁有預見長遠後果的想像力，也能靠教育與自覺培養真正的無私。我們是地球上唯一能夠起身反抗「自私複製者暴政」的物種——基因與迷因塑造了我們，卻不必永遠支配我們。</p><p class="thought-question">🤔 思考：你腦中最頑固的某個信念，究竟是因為「它是真的」才留下，還是因為「它特別擅長被複製」才留下？</p>',
      en: '<p><strong>Core claim:</strong> Genes are not the only replicator in the universe. Within human culture a new replicator has appeared -- the meme: a tune, an idea, a slogan, a fashion, a belief. Like a gene, it copies itself from one brain to another, spreading, competing, and evolving through imitation and transmission.</p><p><strong>The argument:</strong> The author holds that the true protagonist of evolution is anything that can copy itself, not any particular chemical molecule. Beyond the gene pool, human brains and culture form a new meme pool. A meme succeeds or fails by the same three qualities: fidelity of copying, longevity of survival, and speed of spread. A catchy, memorable, easily transmitted idea multiplies fast across minds, and not necessarily because it benefits its hosts -- just as some genes need not benefit their vehicles. Memes also compete for scarce resources: human attention, memory capacity, and airtime.</p><div class="section-break">◆ ◆ ◆</div><p><strong>Key example:</strong> The author points to the idea of God. Its power to cross millennia and cultures owes little to being proven true; rather, as a meme it has high survival value -- it answers a deep human hunger for meaning and comfort, and it usually travels bundled with a whole self-reinforcing complex of memes (faith, an afterlife, ritual) that prop each other up and resist doubt, so it keeps copying itself down the generations.</p><p><strong>Takeaway:</strong> We are vehicles for both genes and memes, and are often pushed along by the interests of these two selfish replicators. Yet the book closes on a note of hope: humans have the foresight to imagine long-term consequences, and can cultivate genuine altruism through education and self-awareness. We are the one species on Earth capable of rebelling against the tyranny of the selfish replicators -- genes and memes made us, but they need not rule us forever.</p><p class="thought-question">🤔 Reflect: That one belief you hold most stubbornly -- did it stay in your head because it is true, or because it is especially good at getting itself copied?</p>'
    }
  }
});
Object.assign(CHAPTER_CONTENT, {
  12: {
    num: { zh: '第 12 章', en: 'Chapter 12' },
    title: { zh: '好人出頭天', en: 'Nice Guys Finish First' },
    epigraph: {
      zh: '「當同一群人得反覆打交道、而且誰也不知道哪一次是最後一次時，善良竟成了最划算的策略。」',
      en: '“When the same players must deal with each other again and again, and no one knows which round is the last, being nice turns out to be the shrewdest strategy of all.”'
    },
    body: {
      zh: `
<p><strong>核心論點：</strong>「自私的基因」聽起來像在為冷酷背書，但道金斯在這一章要證明相反的事——在許多真實情境裡，最能讓基因流傳下去的，恰恰是「合作」而非「彼此坑殺」。關鍵不在道德，而在互動有沒有「未來」：只要同一批對手會一而再、再而三地相遇，善意就能靠純粹的自利邏輯站穩腳跟，好人反而笑到最後。</p>
<p><strong>論證：</strong>單次的囚徒困境裡，理性的算計會把雙方逼向互相背叛，因為不管對方怎麼選，自己背叛都比較划算——結果兩敗俱傷。但如果同樣的兩方要玩很多輪、且不知道哪一輪收場（這就是「重複囚徒困境」iterated Prisoner's Dilemma），計算就翻轉了：今天坑對方，明天就會被報復；今天釋出善意並得到回應，雙方可以長期共享比互咬更高的收益。於是「陰影中的未來」——往後還要見面這件事——就成了讓合作演化出來的引擎。</p>
<div class="section-break">◆ ◆ ◆</div>
<p><strong>關鍵實例：</strong>政治學者 Axelrod 舉辦了一場電腦程式競賽，邀各方高手提交策略，兩兩對戰重複囚徒困境、累積分數。出乎意料，奪冠的不是精心算計、伺機占便宜的複雜程式，而是全場最簡單的一個——「以牙還牙」（Tit-for-Tat）：第一步先合作，之後就完全複製對方上一步的動作。它勝在四個特質：<strong>善良</strong>（絕不率先背叛）、<strong>報復</strong>（對方一背叛立刻回擊，不當濫好人）、<strong>寬恕</strong>（對方一回頭合作就既往不咎，不記仇）、<strong>不忌妒</strong>（從不追求「贏過對手」，只求把自己這局做好）。那些想占盡便宜的「壞」策略，短期或許領先，長期卻在一次次報復中把彼此拖垮。</p>
<p><strong>啟示：</strong>合作不必靠有意識的善念或高尚情操，也能從純粹自利的基因裡自然長出來——它只需要一個條件：重複相遇、且結局未知。這替自然界大量的互惠行為給了根基，也點出人類社會的一個深意：把關係變成「還會再見面」的長局，往往比任何說教都更能催生善意。值得注意的是，以牙還牙從不「贏過」任何單一對手，卻贏得了整場賽局——好人出頭，靠的不是打敗別人，而是不斷促成雙贏。</p>
<p class="thought-question">🤔 思考：如果合作之所以出現，靠的是「往後還要再見面」，那麼在一個人人匿名、一次性交易、誰也不會再遇到誰的環境裡，善意會不會反而先枯死？我們該如何刻意替彼此製造「未來」？</p>`,
      en: `
<p><strong>Core claim:</strong> "The selfish gene" sounds like a licence for ruthlessness, but in this chapter Dawkins argues the opposite: in a great many real situations, what best carries genes forward is cooperation, not mutual sabotage. The trick has nothing to do with morality and everything to do with whether an interaction has a future. As long as the same players keep meeting again and again, goodwill can pay off on pure self-interest alone, and the nice guys end up ahead.</p>
<p><strong>The argument:</strong> In a one-shot Prisoner's Dilemma, cold calculation drives both sides to betray, because whatever the other does, defecting scores better for you; the result is mutual ruin. But if the same two parties must play many rounds without knowing which round will be the last (this is the iterated Prisoner's Dilemma), the arithmetic flips: cheat today and you get punished tomorrow; offer goodwill and have it returned, and both sides can share a payoff far higher than mutual biting ever yields. So the shadow of the future, the mere fact that you will meet again, becomes the engine that lets cooperation evolve.</p>
<div class="section-break">◆ ◆ ◆</div>
<p><strong>Key example:</strong> The political scientist Axelrod ran a computer tournament, inviting experts to submit strategies that would play the iterated Prisoner's Dilemma against each other and rack up points. Surprisingly, the winner was not some elaborate program that schemed for openings to exploit, but the simplest entry of all, Tit-for-Tat: cooperate on the first move, then simply copy whatever the opponent did last time. It won on four traits: it was <strong>nice</strong> (never the first to defect), <strong>retaliatory</strong> (it hit back at once when cheated, refusing to be a pushover), <strong>forgiving</strong> (the moment the other returned to cooperation, it let bygones be bygones), and <strong>not envious</strong> (it never tried to beat its rival, only to play its own hand well). The greedy strategies that grabbed every advantage might lead early, but over the long run they dragged each other down in cycles of retaliation.</p>
<p><strong>Takeaway:</strong> Cooperation need not depend on conscious kindness or lofty virtue; it can grow naturally out of purely selfish genes, given one condition: repeated encounters with an unknown ending. This grounds the vast amount of reciprocity we see in nature, and it carries a lesson for human society too: turning a relationship into a long game where you will meet again does more to breed goodwill than any sermon. Note the deep point: Tit-for-Tat never beats any single opponent, yet it wins the whole tournament. Nice guys finish first not by defeating others, but by relentlessly making win-win happen.</p>
<p class="thought-question">🤔 Reflect: If cooperation arises because we will meet again, then in a world of anonymous, one-off transactions where no one ever crosses paths twice, might goodwill be the first thing to wither? How might we deliberately manufacture a future for one another?</p>`
    }
  },
  13: {
    num: { zh: '第 13 章', en: 'Chapter 13' },
    title: { zh: '基因的長臂', en: 'The Long Reach of the Gene' },
    epigraph: {
      zh: '「基因的效應不會乖乖停在皮膚邊界——它能伸出身體之外，把整個世界都納進自己的表現型。」',
      en: '“A gene\'s effects do not politely stop at the edge of the skin; they can reach out beyond the body and fold the wider world into the phenotype.”'
    },
    body: {
      zh: `
<p><strong>核心論點：</strong>本書一路主張要從「基因的視角」（gene's-eye view）看演化。到了這最後一章，道金斯把這個視角推到最大膽的盡頭：基因的影響力，根本不必被身體的邊界關住。基因造出的效應（也就是「表現型」）可以「伸出去」，改造身體之外的世界。這就是他提出的「延伸的表現型」（extended phenotype）——把整個外在環境，都看成基因為了複製自己而打造的工具。</p>
<p><strong>論證：</strong>我們習慣認為基因只管製造牙齒、羽毛、行為這類「體內」性狀。但道金斯提醒：天擇真正篩選的，是基因「造成了什麼結果、讓自己更容易被傳下去」——而結果落在皮膚裡面還是外面，並無本質差別。海狸的水壩不是海狸身體的一部分，卻同樣是「造壩基因」為了自身存續所產生的效應；那道壩改變了整片地景，只為讓造它的基因活得更好。既然如此，把水壩、蜘蛛的網、鳥的巢都算進基因的表現型，在邏輯上完全一致。表現型的界線，該由「基因效應延伸到哪裡」來畫，而不是由皮膚來畫。</p>
<div class="section-break">◆ ◆ ◆</div>
<p><strong>關鍵實例：</strong>海狸的基因造出水壩，淹出一片池塘，這是延伸表現型最乾淨的例子——一個離身體很遠、卻明明白白由基因塑造的結構。石蠶蛾的幼蟲用石礫與碎屑黏成一只精巧的護巢，那巢就是牠基因的延伸作品，選材與造型都寫在基因裡。最驚人的是寄生蟲：某些寄生蟲能操縱宿主的行為，讓宿主做出對自己有害、卻剛好幫寄生蟲完成生活史的事。此時，寄生蟲的基因竟伸進了「另一個生物的身體」，遙控牠的行動——表現型不只越過了皮膚，還越過了「個體」的界線。</p>
<p><strong>啟示：</strong>「延伸的表現型」是全書基因視角的收束與登頂：真正的演化主角，始終是那個追求自我複製的基因；身體、行為、乃至身外的水壩與被操縱的宿主，都只是基因為了流傳而伸出的「長臂」。這也是回望全書的最後一步——我們與萬物看似獨立自主，其實都是這些不朽複製子借來、用來航向下一代的載具。看清這一點，並不叫我們認命於自私；正因為人類獨有反思與遠見，我們才有可能起身反抗造出我們的基因，選擇合作、選擇善意，成為地球上唯一能對抗自身出身的生物。</p>
<p class="thought-question">🤔 思考：若海狸的壩、蜘蛛的網、被寄生蟲遙控的宿主都算基因伸出的長臂，那麼人類造的城市、寫下的法律、打造的機器，是不是也都是我們基因（與文化）的延伸表現型？而當我們清楚看見這條長臂，是否就有了掙脫它、重新選擇的自由？</p>`,
      en: `
<p><strong>Core claim:</strong> Throughout the book Dawkins has urged us to see evolution from the gene's-eye view. In this closing chapter he pushes that view to its boldest conclusion: a gene's influence need not be caged inside the body at all. The effects a gene produces (its phenotype) can reach out and reshape the world beyond the body. This is his idea of the extended phenotype: treating the whole external environment as a tool that genes build to copy themselves.</p>
<p><strong>The argument:</strong> We are used to thinking genes only make in-body traits like teeth, feathers, and behaviour. But Dawkins points out that what natural selection really screens for is the consequences a gene produces that make it more likely to be passed on, and whether those consequences land inside or outside the skin makes no fundamental difference. A beaver's dam is no part of the beaver's body, yet it is just as much an effect that dam-building genes produce for their own survival; the dam remakes an entire landscape purely so its builder genes can prosper. That being so, counting dams, spiders' webs, and birds' nests as part of a gene's phenotype is perfectly consistent. The boundary of the phenotype should be drawn by how far a gene's effects reach, not by the skin.</p>
<div class="section-break">◆ ◆ ◆</div>
<p><strong>Key example:</strong> A beaver's genes build a dam and flood a pond into being; this is the cleanest case of an extended phenotype, a structure far from the body yet plainly shaped by genes. A caddisfly larva glues pebbles and debris into an elaborate protective case, and that case is its genes' extended handiwork, with the choice of materials and the design written into the genes. Most striking of all are parasites: some can manipulate a host's behaviour, driving the host to do things that harm itself but happen to help the parasite complete its life cycle. Here a parasite's genes reach right inside another creature's body and remote-control its actions; the phenotype has crossed not only the skin but the boundary of the individual itself.</p>
<p><strong>Takeaway:</strong> The extended phenotype is where the book's gene's-eye view reaches its summit and comes to rest: the true protagonist of evolution has been, all along, the gene bent on copying itself; bodies, behaviours, and even dams and hijacked hosts out in the world are merely the long reach it extends in order to persist. This is the last step of the whole journey: we and every living thing, seemingly independent and self-directed, are in truth vehicles that these immortal replicators borrow to sail into the next generation. Seeing this does not condemn us to selfishness. Precisely because humans alone possess reflection and foresight, we alone can rise up against the genes that made us, choose cooperation, choose goodwill, and become the one creature on earth that can defy its own origins.</p>
<p class="thought-question">🤔 Reflect: If a beaver's dam, a spider's web, and a parasite-controlled host all count as the long reach of the gene, then are the cities we build, the laws we write, and the machines we make also extended phenotypes of our genes (and culture)? And once we see that long arm clearly, do we thereby gain the freedom to break from it and choose anew?</p>`
    }
  }
});
